SiaFoundation/web

- .changeset/curly-monkeys-search.md
- .changeset/ten-needles-attack.md
- .changeset/thick-dodos-know.md
- apps/hostd/components/Wallet/index.tsx
- apps/hostd/dialogs/HostdTransactionDetailsDialog.tsx
- apps/renterd/components/Node/index.tsx
- apps/renterd/components/Wallet/index.tsx
- apps/renterd/contexts/contracts/index.tsx
- apps/renterd/dialogs/RenterdTransactionDetailsDialog.tsx
- apps/renterd/hooks/useSyncStatus.ts
- libs/design-system/src/app/TransactionDetailsDialog.tsx
- libs/design-system/src/app/TxPoolList.tsx
- libs/design-system/src/app/WalletBalanceEvolution.tsx
- libs/design-system/src/components/ChartXY/index.tsx
- libs/design-system/src/lib/entityTypes.ts
- libs/react-renterd/src/siaTypes.ts
Closes https://github.com/SiaFoundation/renterd/issues/378
> fix: renterd breaking API changes, wallet evolution and transactions

- .changeset/giant-poets-remember.md
- .changeset/tasty-geese-explode.md
- apps/hostd/components/Node/Logs.tsx
- apps/hostd/components/Node/index.tsx
- apps/hostd/contexts/metrics/index.tsx
- libs/design-system/src/core/Codeblock.tsx
- libs/react-hostd/src/api.ts
> hostd log view in node overview

- .changeset/metal-socks-study.md
- apps/hostd/components/DirectorySelectMenu/DirectorySelectCmd/DirectoryCreate.tsx
- apps/hostd/components/DirectorySelectMenu/DirectorySelectCmd/DirectoryParentItem.tsx
- apps/hostd/components/DirectorySelectMenu/DirectorySelectCmd/index.tsx
- apps/hostd/components/DirectorySelectMenu/index.tsx
- apps/hostd/dialogs/VolumeCreateDialog.tsx
- apps/hostd/lib/system.spec.ts
- apps/hostd/lib/system.ts
- libs/react-hostd/src/api.ts
https://github.com/SiaFoundation/hostd/issues/47
> hostd custom location path for volume creation

- .changeset/fair-colts-happen.md
- .changeset/moody-lizards-sort.md
- .changeset/olive-shoes-attack.md
- .changeset/tall-drinks-camp.md
- .changeset/ten-flies-divide.md
- .changeset/tender-roses-suffer.md
- apps/hostd/components/Contracts/ContractDropdownMenu.tsx
- apps/hostd/components/Home/HomeStorage.tsx
- apps/hostd/contexts/contracts/columns.tsx
- apps/hostd/contexts/metrics/index.tsx
- libs/design-system/src/core/Link.tsx
- libs/design-system/src/lib/chartData.ts
- libs/react-hostd/src/api.ts
before/after:
<p float="left">
</p>
> hostd contract integrity check, fix metrics spike, disable storage totals, metrics collateral based on multiplier

- .changeset/warm-news-know.md
- apps/hostd/components/Home/index.tsx
- apps/hostd/contexts/metrics/types.tsx
- libs/data-sources/src/lib/feedRssSync.ts
- libs/data-sources/src/lib/notion/articles.ts
- libs/data-sources/src/lib/notion/assets.ts
- libs/data-sources/src/lib/notion/feed.ts
- libs/data-sources/src/lib/notion/grantCommittee.ts
- libs/data-sources/src/lib/notion/notion.ts
- libs/data-sources/src/lib/notion/projects.ts
- libs/data-sources/src/lib/notion/team.ts
- libs/design-system/src/app/TestnetWarningBanner.tsx
- libs/design-system/src/lib/chartData.ts
- libs/react-hostd/src/api.ts
- Metrics now support a 1 day time range with 5 minute intervals. https://github.com/SiaFoundation/hostd/issues/139
> hostd metrics 1 day time range with 5 minute intervals, website content validation

- .changeset/fifty-pillows-heal.md
- apps/hostd/contexts/metrics/index.tsx
- apps/hostd/contexts/metrics/useNowAtInterval.tsx
- libs/design-system/src/lib/chartData.ts
- The metrics time range now automatically updates and refreshes the data at a rate equal to the selected data interval. https://github.com/SiaFoundation/hostd/issues/128
> fix: automatically reset time range

- .changeset/big-snails-jam.md
- .changeset/great-numbers-shake.md
- .changeset/silly-doors-clean.md
- .changeset/soft-mails-greet.md
- .changeset/sweet-cows-sit.md
- .changeset/ten-brooms-raise.md
- apps/explorer/components/Home/index.tsx
- apps/hostd/components/Node/index.tsx
- apps/hostd/components/Volumes/VolumeContextMenu.tsx
- apps/hostd/contexts/metrics/index.tsx
- apps/hostd/contexts/metrics/types.tsx
- apps/hostd/contexts/volumes/columns.tsx
- libs/react-hostd/src/api.ts
- https://github.com/SiaFoundation/hostd/issues/142
- https://github.com/SiaFoundation/hostd/issues/170
- https://github.com/SiaFoundation/hostd/issues/114
> hostd volume operations cancel, node network height, bandwidth metrics

- .changeset/dull-pears-sing.md
- apps/renterd/contexts/config/fields.tsx
https://github.com/SiaFoundation/renterd/issues/683
https://github.com/SiaFoundation/renterd/issues/681
> renterd upload packing switch and explanation

- .changeset/fuzzy-moles-cross.md
- apps/hostd/contexts/config/fields.tsx
- apps/hostd/contexts/config/index.tsx
- The configuration now shows suggestions for pricing, collateral, and other settings. https://github.com/SiaFoundation/hostd/issues/203
> hostd configuration suggestions

- .changeset/beige-toes-explode.md
- .changeset/tough-ducks-tap.md
- apps/renterd/components/Files/FilesStatsMenu/FilesStatsMenuHealth.tsx
- libs/react-renterd/src/bus.ts
- The file stats overall health now uses the min health reported by the object stats endpoint.
> renterd object min health stat

- .changeset/shiny-clouds-obey.md
- apps/renterd/components/Files/FilesFilterDirectoryMenu/index.tsx
- apps/renterd/components/Files/FilesStatsMenu/FilesStatsMenuWarnings.tsx
- apps/renterd/components/Files/useCanUpload.tsx
- File uploads are now disabled if the blockchain is not fully synced.
> fix: renterd uploads require sync

- .changeset/khaki-points-smile.md
- apps/renterd/contexts/hosts/columns.tsx
- apps/renterd/contexts/hosts/dataset.ts
- apps/renterd/contexts/hosts/types.tsx
- libs/react-renterd/src/autopilot.ts
https://github.com/SiaFoundation/renterd/pull/805
> renterd gouging breakdown changes

- .changeset/khaki-badgers-leave.md
- apps/explorer/jest.config.ts
- apps/hostd/jest.config.ts
- apps/renterd/jest.config.ts
- apps/walletd/jest.config.ts
- apps/website/jest.config.ts
- libs/design-system/jest.config.ts
- libs/design-system/package.json
- libs/design-system/src/lib/clipboard.ts
- libs/fonts/jest.config.ts
- libs/react-icons/jest.config.ts
- package-lock.json
- package.json
- Fixed an issue with the copy to clipboard feature. https://github.com/SiaFoundation/hostd/issues/247
> fix: copy to clipboard

- .changeset/hip-crabs-scream.md
- .changeset/wise-shoes-ring.md
- apps/renterd/components/Contracts/ContractsCmd/ContractsFilterCmd/ContractFilterCmdGroups/ContractSet.tsx
- apps/renterd/components/Contracts/ContractsCmd/ContractsFilterCmd/ContractFilterCmdGroups/index.tsx
- apps/renterd/components/Contracts/ContractsCmd/ContractsFilterCmd/ContractFilterNav/index.tsx
- apps/renterd/components/Contracts/ContractsFilterContractSetDialog.tsx
- apps/renterd/contexts/contracts/columns.tsx
- apps/renterd/contexts/contracts/index.tsx
- apps/renterd/contexts/contracts/types.ts
- apps/renterd/contexts/dialog.tsx
- apps/walletd/dialogs/WalletAddressesAddDialog.tsx
- apps/walletd/dialogs/WalletAddressesGenerateLedgerDialog/index.tsx
- apps/walletd/dialogs/WalletAddressesGenerateSeedDialog/index.tsx
- apps/walletd/dialogs/WalletUnlockDialog.tsx
- apps/walletd/dialogs/WalletUpdateDialog/index.tsx
- libs/design-system/src/form/useDialogFormHelpers.ts
- libs/design-system/src/index.ts
- libs/react-renterd/src/bus.ts
- libs/react-renterd/src/siaTypes.ts
- Fixed an issue displaying the contract sets column data on the contracts explorer.
- Contracts can now be filtered by contract set.
> renterd fix issue displaying contract sets, ability to filter by contract set

- .changeset/many-tigers-guess.md
- apps/hostd/components/Config/AnnounceButton.tsx
- apps/hostd/components/Config/ConfigActions.tsx
- apps/hostd/components/Config/ConfigContextMenu.tsx
- apps/hostd/components/Config/index.tsx
- apps/hostd/contexts/config/index.tsx
- apps/hostd/contexts/metrics/useNowAtInterval.tsx
- apps/renterd/components/Config/ConfigActions.tsx
- apps/renterd/components/Config/ConfigContextMenu.tsx
- apps/renterd/components/Config/index.tsx
- apps/renterd/contexts/config/index.tsx
- libs/design-system/package.json
- libs/design-system/src/index.ts
- libs/design-system/src/lib/clipboard.ts
- libs/design-system/src/lib/nodeToImage.tsx
- package-lock.json
- package.json
- The configuration page now has menu options to download or copy an image of the current configuration for easier sharing.
> renterd and hostd config sharing options

- .changeset/rotten-dots-reply.md
- apps/hostd/components/Config/AnnounceButton.tsx
- apps/hostd/contexts/config/index.tsx
- apps/hostd/contexts/config/useOnValid.tsx
- libs/react-hostd/src/api.ts
- The announce button is now disabled unless the net address does not match the last announcement. https://github.com/SiaFoundation/hostd/issues/248
> hostd announce button states

- README.md
I thought newcomers could use more guidance on development practices for this repo. Added changeset, commit, and test instructions under the development section.
> Updated README.md with development instructions

- .changeset/beige-walls-smoke.md
- apps/hostd/contexts/config/fields.tsx
- The bandwidth settings for egress and ingress now have clearer descriptions.
> hostd bandwidth setting descriptions are now more clear

- .changeset/two-ducks-act.md
- libs/react-renterd/src/bus.ts
- libs/react-renterd/src/siaTypes.ts
- libs/react-renterd/src/worker.ts
- Add useMultipartUploadCreate, useMultipartUploadComplete, useMultipartUploadAbort, useMultipartUploadAddPart, useMultipartUploadChunk, useMultipartUploadListUploads, useMultipartUploadListParts.
> feat: renterd multipart upload hooks

- apps/explorer/jest.config.ts
- apps/hostd/jest.config.ts
- apps/renterd/jest.config.ts
- apps/walletd/jest.config.ts
- apps/website/jest.config.ts
- libs/design-system/jest.config.ts
- libs/fonts/jest.config.ts
- libs/next/jest.config.ts
- libs/react-core/jest.config.ts
- libs/react-hostd/jest.config.ts
- libs/react-icons/jest.config.ts
- libs/react-renterd/jest.config.ts
- libs/react-sia-central/jest.config.ts
- libs/react-walletd/jest.config.ts
- libs/sdk/jest.config.ts
- libs/sia-central/jest.config.ts
- libs/types/jest.config.ts
- libs/units/jest.config.ts
- Required jest configuration changes for multipart uploader tests against a class with private methods syntax.
> chore: class private method support to jest

- .changeset/tough-shrimps-protect.md
- apps/renterd/components/Files/FilesExplorerModeContextMenu.tsx
- apps/renterd/components/TransfersBar.tsx
- apps/renterd/contexts/filesManager/index.spec.tsx
- apps/renterd/contexts/filesManager/index.tsx
- apps/renterd/contexts/uploads/index.tsx
- Fixed an issue navigating back to the active explorer mode from the uploads list.
> fix: renterd files mode navigation

- .changeset/red-ways-decide.md
- apps/renterd/contexts/alerts/data.tsx
- The lost sector alert now shows the number of lost sectors.
> fix: renterd lost sector alert

- .changeset/honest-nails-laugh.md
- apps/hostd/components/Config/index.tsx
- apps/renterd/components/Config/index.tsx
> fix: center configuration panel

- README.md
- libs/design-system/package.json
- libs/react-icons/package.json
- Updated libraries listed in readme.
> docs: update libraries in readme

- .changeset/breezy-moles-provide.md
- .changeset/cuddly-plums-cry.md
- .changeset/purple-gifts-reflect.md
- .changeset/sharp-books-kick.md
- .changeset/strong-buses-remember.md
- apps/renterd/components/Config/ConfigStats.tsx
- apps/renterd/components/Config/Recommendations.tsx
- apps/renterd/components/Config/index.tsx
- apps/renterd/contexts/config/fields.tsx
- apps/renterd/contexts/config/index.tsx
- apps/renterd/contexts/config/transform.spec.ts
- apps/renterd/contexts/config/transformDown.ts
- apps/renterd/contexts/config/transformUp.spec.ts
- apps/renterd/contexts/config/transformUp.ts
- apps/renterd/contexts/config/types.ts
- apps/renterd/contexts/config/useAutopilotEvaluations.tsx
- apps/renterd/contexts/config/useForm.tsx
- apps/renterd/contexts/config/useOnValid.tsx
- apps/renterd/contexts/config/useResources.tsx
- apps/renterd/contexts/config/useSyncContractSet.tsx
- apps/renterd/contexts/config/utils.spec.ts
- apps/renterd/contexts/config/utils.ts
- libs/design-system/src/app/PanelMenuSetting.tsx
- libs/design-system/src/form/ConfigurationPanel.tsx
- libs/design-system/src/form/useFormInit.tsx
- libs/design-system/src/form/useFormServerSynced.tsx
- libs/renterd-react/src/autopilot.ts
- The renterd configuration page now recommends specific changes to settings to match with more hosts.
- Configuration settings that the user has not modified will be kept in sync with remote values that change (renterd & hostd).
- Fixed a few other related bugs.
> feat: renterd config evaluation

- .changeset/khaki-peas-return.md
- apps/hostd/contexts/config/fields.tsx
- Moved the pinned currency change threshold to advanced mode settings.
> fix: hostd pinned threshold advanced

- .changeset/shaggy-peas-sip.md
- apps/hostd/dialogs/HostdTransactionDetailsDialog.tsx
- apps/hostd/dialogs/VolumeDeleteDialog.tsx
- apps/hostd/dialogs/VolumeResizeDialog.tsx
- apps/renterd/dialogs/RenterdTransactionDetailsDialog.tsx
- Fixed an issue where the transaction information would not show in the dialog.
> fix: transaction details dialog

- apps/walletd-e2e/src/specs/seedSendSiacoin.spec.ts
- The change address in the test was not for the same wallet
> fix: walletd send siacoin test change address

- .changeset/cyan-grapes-play.md
- apps/website/components/DownloadSection.tsx
- Software downloads now also list system requirements. https://github.com/SiaFoundation/web/issues/553
> feat: website add system requirements

- .changeset/calm-hounds-chew.md
- .changeset/friendly-drinks-draw.md
- libs/renterd-js/src/bus.ts
- libs/renterd-react/src/bus.ts
- libs/renterd-types/src/bus.ts
- Added the contracts prunable API.
- Added the contract size API.
> fix: renterd add contract prunable and size APIs

- .changeset/angry-badgers-bathe.md
- apps/explorer/config/index.ts
- apps/explorer/config/testnet-zen.ts
- apps/explorer/hooks/useFaucetFund.ts
- apps/explorer/hooks/useFaucetStatus.ts
- The faucet API was moved, this updates to the new endpoint.
> fix: explorer faucet api

- .changeset/poor-seahorses-matter.md
- libs/renterd-js/src/bus.ts
- libs/renterd-react/src/bus.ts
- libs/renterd-types/package.json
- libs/renterd-types/src/types.ts
- Add price pinning configuration API.
> feat: renterd price pinning api

- apps/hostd-e2e/src/fixtures/beforeTest.ts
- apps/hostd-e2e/src/fixtures/configResetAllSettings.ts
- apps/hostd-e2e/src/fixtures/login.ts
- apps/hostd-e2e/src/fixtures/volumes.ts
- apps/hostd-e2e/src/specs/config.spec.ts
- apps/hostd-e2e/src/specs/login.spec.ts
- apps/hostd-e2e/src/specs/volumes.spec.ts
- apps/hostd-e2e/src/specs/wallet.spec.ts
- apps/hostd/components/OnboardingBar.tsx
- apps/hostd/components/Volumes/VolumeContextMenu.tsx
> Tests pass on final e2e PR: https://github.com/SiaFoundation/web/pull/726
- Migrate all hostd e2e tests to use clusterd.
> refactor(hostd-e2e): migrate tests to clusterd

- apps/walletd-e2e/src/fixtures/beforeTest.ts
- apps/walletd-e2e/src/fixtures/events.ts
- apps/walletd-e2e/src/fixtures/login.ts
- apps/walletd-e2e/src/fixtures/preferences.ts
- apps/walletd-e2e/src/fixtures/siascan.ts
- apps/walletd-e2e/src/fixtures/skip.ts
- apps/walletd-e2e/src/fixtures/wallet.ts
- apps/walletd-e2e/src/specs/login.spec.ts
- apps/walletd-e2e/src/specs/seedGenerateAddresses.spec.ts
- apps/walletd-e2e/src/specs/seedSendSiacoin.spec.ts
- apps/walletd-e2e/src/specs/wallet.spec.ts
- apps/walletd/components/RescanStatus.tsx
- apps/walletd/components/WalletsList/WalletsActionsMenu.tsx
- libs/walletd-react/src/api.ts
> Tests pass on final e2e PR: https://github.com/SiaFoundation/web/pull/726
- Migrate all walletd e2e tests to use clusterd.
> refactor(walletd-e2e): migrate tests to clusterd

- apps/renterd/components/Config/ConfigStats.tsx
- apps/renterd/components/Config/ShouldPinSwitch.tsx
- apps/renterd/components/Config/index.tsx
- apps/renterd/components/Config/useEstimatedSpending.tsx
- apps/renterd/contexts/config/deriveAllowance.spec.ts
- apps/renterd/contexts/config/deriveAllowance.ts
- apps/renterd/contexts/config/fieldTips/Allowance.tsx
- apps/renterd/contexts/config/fieldTips/MaxDownloadPrice.tsx
- apps/renterd/contexts/config/fieldTips/MaxRPCPrice.tsx
- apps/renterd/contexts/config/fieldTips/MaxStoragePrice.tsx
- apps/renterd/contexts/config/fieldTips/MaxUploadPrice.tsx
- apps/renterd/contexts/config/fieldTips/Tip.tsx
- apps/renterd/contexts/config/fields.tsx
- apps/renterd/contexts/config/index.tsx
- apps/renterd/contexts/config/resources.ts
- apps/renterd/contexts/config/transform.spec.ts
- apps/renterd/contexts/config/transformDown.ts
- apps/renterd/contexts/config/transformUp.ts
- apps/renterd/contexts/config/types.ts
- apps/renterd/contexts/config/useAllowanceDerivedPricing.tsx
- apps/renterd/contexts/config/useAutopilotEvaluations.tsx
- apps/renterd/contexts/config/useAverages.tsx
- apps/renterd/contexts/config/useForm.tsx
- apps/renterd/contexts/config/useFormExchangeRate.tsx
- apps/renterd/contexts/config/useOnValid.tsx
- apps/renterd/contexts/config/useRedundancyMultiplier.tsx
- apps/renterd/contexts/config/useSyncContractSet.tsx
> Strict mode refactoring part 3/3: no changes to functionality.
- Update renterd app to TypeScript strict mode 2/2: config feature.
- Primarily adds all missing strict null checks.
- Refine config data types to be more specific.
> refactor(renterd): typescript strict mode for config feature

- .changeset/few-deers-appear.md
- apps/hostd-e2e/src/fixtures/clearToasts.ts
- apps/renterd-e2e/src/fixtures/clearToasts.ts
- apps/renterd-e2e/src/fixtures/files.ts
- apps/renterd-e2e/src/specs/files.spec.ts
- apps/renterd/components/Hosts/HostContextMenuFromKey.tsx
- apps/renterd/contexts/alerts/data.tsx
- apps/renterd/contexts/contracts/useContractMetrics.tsx
- apps/renterd/contexts/filesDirectory/dataset.tsx
- apps/renterd/contexts/filesFlat/dataset.tsx
- apps/renterd/lib/multipartUpload.ts
- internal/cluster/go.mod
- internal/cluster/go.sum
- libs/renterd-types/src/bus.ts
- libs/renterd-types/src/worker.ts
- All query parameters are now lowercased for API consistency.
> refactor(renterd): query param consistency

- apps/explorer/next-env.d.ts
- apps/hostd/next-env.d.ts
- apps/renterd/next-env.d.ts
- apps/walletd/next-env.d.ts
- apps/website/next-env.d.ts
- libs/fonts/package.json
- libs/next/package.json
- package-lock.json
- package.json
- Upgrade next version used across repo and projects.
> chore: upgrade next

- .changeset/mean-numbers-train.md
- libs/renterd-js/src/bus.ts
- libs/renterd-react/src/bus.ts
- libs/renterd-types/src/bus.ts
- Added consensus network API.
> feat(renterd): add consensus network API

- .changeset/giant-seals-tickle.md
- .changeset/light-games-unite.md
- apps/renterd/contexts/config/transform.spec.ts
- apps/renterd/contexts/config/transformUp.ts
- libs/renterd-js/src/bus.ts
- libs/renterd-react/src/bus.ts
- libs/renterd-types/src/bus.ts
- libs/renterd-types/src/types.ts
- Removed autopilots API.
- Add enabled flag to autopilot config type.
> refactor(renterd-libs): remove autopilots API

- .changeset/fifty-dogs-study.md
- .changeset/strange-ravens-joke.md
- apps/hostd-e2e/src/fixtures/navigate.ts
- apps/hostd-e2e/src/specs/volumes.spec.ts
- libs/design-system/src/app/AlertsDialog/index.tsx
- Fixed an issue where the list of alerts was not showing.
> fix(hostd): alerts list not showing

- .changeset/poor-apples-promise.md
- apps/website/content/mica.ts
- The mica ticker has changed.
> website: mica ticker

- .changeset/early-rockets-count.md
- libs/renterd-js/src/bus.ts
- libs/renterd-react/src/bus.ts
- libs/renterd-types/src/index.ts
- Added the auth API.
- Subject to change based on https://github.com/SiaFoundation/renterd/pull/1806
> feat(renterd-libs): add auth api

- .changeset/fluffy-timers-allow.md
- apps/renterd-e2e/src/specs/files.spec.ts
- apps/renterd/components/Files/FilesViewDropdownMenu.tsx
- apps/renterd/components/FilesDirectory/FilesActionsMenu.tsx
- apps/renterd/components/FilesDirectory/FilesExplorer.tsx
- apps/renterd/components/FilesFlat/FilesActionsMenu.tsx
- apps/renterd/components/FilesFlat/FilesExplorer.tsx
- apps/renterd/contexts/filesDirectory/dataset.tsx
- apps/renterd/contexts/filesDirectory/index.tsx
- apps/renterd/contexts/filesFlat/dataset.tsx
- apps/renterd/contexts/filesFlat/index.tsx
- apps/renterd/contexts/filesManager/dataset.tsx
- apps/renterd/contexts/filesManager/index.tsx
- libs/design-system/src/hooks/useTableState.ts
- Fixed an issue where the global files view was not showing full file paths.
> fix(renterd): files global view full keys

- .changeset/blue-trainers-laugh.md
- libs/design-system/src/components/ValueCopyable.tsx
- libs/design-system/src/components/ValueFiat.tsx
- libs/design-system/src/components/ValueNum.tsx
- libs/design-system/src/components/ValueSc.tsx
- libs/design-system/src/components/ValueSf.tsx
- Added labeledBy prop to value components.
> feat(design-system): value label support

- apps/explorer/app/fallback.ts
- apps/explorer/app/layout.tsx
- Adds initial server-rendering support for currency values with user-specific exchange rates.
> feat(explorer): server-side currency data

- .changeset/ten-geckos-rest.md
- libs/e2e/package.json
- libs/sia-central-mock/package.json
- libs/walletd-mock/package.json
- package-lock.json
- Ensure we are running the latest version of playwright libraries.
> chore: upgrade playwright

- .changeset/nervous-points-remember.md
- .changeset/ninety-moons-exercise.md
- .changeset/shaggy-lies-matter.md
- libs/renterd-js/src/bus.ts
- libs/renterd-react/src/bus.ts
- libs/renterd-types/src/bus.ts
- libs/renterd-types/src/types.ts
- Added contract formation API.
- Updated payloads for contract lock and release APIs.
- Added new fields to Contract type.
> feat(renterd-libs): add contract form api

- .changeset/nine-trainers-impress.md
- apps/explorer/app/contract/[id]/opengraph-image.tsx
- apps/explorer/lib/time.ts
> fix(explorer): shorten contract opengraph image date display

- .changeset/calm-boats-tease.md
- .changeset/yellow-beans-switch.md
- libs/hostd-js/src/api.ts
- libs/hostd-react/src/api.ts
- libs/hostd-types/src/api.ts
- libs/hostd-types/src/types.ts
- libs/types/src/v2.ts
- Added V2 contracts API.
- Add capacity field to V2FileContract.
> feat(hostd-libs): add v2 contracts api

- .changeset/tricky-fishes-breathe.md
- libs/explored-types/src/types.ts
- libs/types/src/core.ts
> feat(types): add V2HostSettings

- .changeset/stupid-rivers-sing.md
- apps/explorer/components/HardforkCountdown/index.tsx
- apps/explorer/components/SyncWarning/index.tsx
- apps/explorer/lib/sync.ts
- The explorer now shows specific syncing and indexing warnings.
> feat(explorer): sync and index warnings

- .changeset/twelve-swans-wait.md
- apps/website/components/Map/index.tsx
- Fixed the map when zero hosts are found.
> fix(website): map zero results

- .changeset/lazy-scissors-happen.md
- libs/explored-types/src/api.ts
This route was changed in https://github.com/SiaFoundation/explored/pull/189
> fix(explored-types): update hostByPubkeyRoute to match new explored location

- commitlint.config.js
- Bump up the max line length for commit body content.
> chore: commitlint body length

- .changeset/two-numbers-glow.md
- apps/walletd/lib/__snapshots__/signSeedV2.spec.ts.snap
- apps/walletd/lib/mocks/mockSeedWallet.ts
- libs/types/src/core.ts
- libs/types/src/v2.ts
- The v2 element structure was changed in core, this matches the change.
> fix(types): v2 element structure change

- .changeset/cyan-gorillas-begin.md
- apps/walletd/lib/mocks/mockConsensusTipState.ts
- libs/hostd-types/src/api.ts
- libs/sdk/src/wallet.mock.ts
- libs/types/src/core.ts
- The siafund and foundation fields on ConsensusState were renamed.
> fix: rename siafund and foundation fields on ConsensusState

- libs/sdk/src/rhp.spec.ts
- libs/sdk/src/wallet.spec.ts
- Tests had some typing issues.
> test(sdk): streamline tests and improve types

- .changeset/fair-planets-give.md
- apps/website/pages/about-sia-foundation/index.tsx
- Fixed the contact email. Thanks @stevefunk (https://github.com/SiaFoundation/web/pull/1053) for catching this! Since that PR was from a fork I could not update it - here is one with conventional commit formatting, a changeset, and uses the variable.
> fix(website): contact email

- .changeset/sharp-cherries-type.md
- libs/sdk/src/types.ts
- libs/sdk/src/wallet.mock.ts
- libs/sdk/src/wallet.spec.ts
- sdk/main.go
- Added a v2TransactionId method to the WASM SDK.
> feat(sdk): v2TransactionId method

- .changeset/small-lizards-call.md
- libs/walletd-types/src/api.ts
- The transaction pool broadcast API now returns the full transaction set.
> feat(walletd-libs): txpool broadcast returns  full transaction set

- .changeset/hip-clocks-know.md
- libs/walletd-js/src/index.ts
- libs/walletd-react/src/api.ts
- libs/walletd-types/src/api.ts
- Added the address output APIs to the walletd JS and React SDKs.
> feat(walletd-libs): add address output APIs

- .changeset/famous-jars-hug.md
- apps/hostd/contexts/alerts/data.tsx
- libs/hostd-types/src/api.ts
Adds the current and latest versions from the versioning alert to the display.
> Update alerts data

- .changeset/blue-eagles-cheat.md
- apps/explorer/components/Transaction/OutputListItem.tsx
- apps/explorer/components/Transaction/index.tsx
- apps/explorer/components/TransactionSkeleton/index.tsx
- apps/explorer/lib/tx.ts
This could benefit from a physical review to ensure values are accurate--they appear to match the address page, which is promising, but someone with a longer history with our chain, challenging assumptions, could be valuable.
> feat(explorer): summarize transactions by address

- .changeset/wet-hotels-rhyme.md
- apps/explorer-e2e/src/specs/block.spec.ts
- apps/explorer-e2e/src/specs/contract.spec.ts
- apps/explorer-e2e/src/specs/tx.spec.ts
- apps/explorer/app/contract/[id]/page.tsx
- apps/explorer/app/tx/[id]/page.tsx
- apps/explorer/components/Block/index.tsx
- apps/explorer/components/Contract/ContractHeader.tsx
- apps/explorer/components/Entity/BlockList.tsx
- apps/explorer/components/Home/index.tsx
- apps/explorer/components/Transaction/TransactionHeader.tsx
- apps/explorer/lib/contracts.ts
Adds version badges to block, transaction, and contract. Tests, too.
> feat(explorer): add version badge to block, transaction, and contract pages

- apps/hostd-e2e/src/specs/config.spec.ts
- apps/renterd-e2e/src/fixtures/beforeTest.ts
- apps/walletd-e2e/src/fixtures/beforeTest.ts
- apps/walletd-e2e/src/fixtures/retryOperation.ts
- apps/walletd-e2e/src/specs/seedSendSiacoin.spec.ts
- apps/walletd-e2e/src/specs/seedSendSiafund.spec.ts
- apps/walletd-e2e/src/specs/wallet.spec.ts
- libs/clusterd/src/index.ts
- Some direct fixes and tweaks to avoid flakiness.
> fix(e2e): renterd, walletd, and hostd e2e fixes

- .changeset/good-lemons-retire.md
- apps/explorer-e2e/src/specs/contract.spec.ts
- apps/renterd/components/Contracts/ContractContextMenu.tsx
- apps/renterd/components/Hosts/HostContextMenuFromKey.tsx
- apps/renterd/components/Hosts/HostsBulkMenu/HostsAddBlocklist.tsx
- apps/renterd/components/Hosts/HostsBulkMenu/HostsRemoveBlocklist.tsx
- apps/renterd/contexts/alerts/data.tsx
- apps/renterd/contexts/hosts/columns.tsx
- apps/renterd/contexts/hosts/dataset.ts
- apps/renterd/contexts/hosts/index.tsx
- apps/renterd/contexts/hosts/types.tsx
- apps/renterd/lib/host.ts
- Fixed an issue where features were using the v1 host netAddress field for v2 hosts, which causes some features to be disabled or not work as expected.
> fix(renterd): normalize v1 and v2 host address

- .changeset/dark-women-marry.md
- apps/indexd/components/Data/Contracts/ContractsTab.tsx
- apps/indexd/components/Data/Contracts/SidePanelContract.tsx
- apps/indexd/components/Data/Contracts/SidePanelContractList.tsx
- apps/indexd/components/Data/Contracts/contractsColumns.tsx
- apps/indexd/components/Data/Contracts/transform.ts
- apps/indexd/components/Data/Contracts/types.ts
- apps/indexd/components/Data/Contracts/useContracts.tsx
- apps/indexd/components/Data/Hosts/hostsColumns.tsx
- apps/indexd/components/Data/Views.tsx
- apps/indexd/components/Data/index.tsx
> feat(indexd): contract explorer

- .changeset/light-nails-grow.md
- apps/explorer/components/Host/HostPricing.tsx
- apps/explorer/components/Host/HostSettings.tsx
- Fix units in storage, download, and upload display text.
> fix(explorer): storage remove dupe month, d/u remove month

- .changeset/bright-tires-rhyme.md
- apps/indexd/components/Data/Accounts/SidePanelAccount.tsx
- apps/indexd/contexts/dialog.tsx
- apps/indexd/dialogs/AccountDeleteDialog.tsx
- Accounts can now be deleted.
> feat(indexd): delete account

- .changeset/twenty-peaches-agree.md
- libs/indexd-js/src/admin.ts
- libs/indexd-react/src/admin.ts
- libs/indexd-types/src/admin/index.ts
- libs/indexd-types/src/admin/types.ts
> feat(indexd-libs): alerts

- .changeset/crazy-dots-carry.md
- .changeset/honest-parts-appear.md
- apps/indexd/components/Data/Alerts/AlertsTab.tsx
- apps/indexd/components/Data/Alerts/SidePanelAlert.tsx
- apps/indexd/components/Data/Alerts/SidePanelAlertList.tsx
- apps/indexd/components/Data/Alerts/alertsColumns.tsx
- apps/indexd/components/Data/Alerts/transform.ts
- apps/indexd/components/Data/Alerts/types.ts
- apps/indexd/components/Data/Alerts/useAlerts.tsx
- apps/indexd/components/Data/Alerts/useAlertsParams.ts
- apps/indexd/components/Data/Alerts/utils.ts
- apps/indexd/components/Data/PanelInfoRow.tsx
- apps/indexd/components/Data/Views.tsx
- apps/indexd/components/Data/index.tsx
- The data explorer now includes alerts.
- Alerts can be dismissed from the detail panel.
> feat(indexd): alerts

- .changeset/old-banks-sin.md
- apps/indexd/components/Data/Keys/SidePanelKeyList.tsx
- apps/indexd/contexts/dialog.tsx
- apps/indexd/dialogs/ConnectKeyCreateDialog.tsx
- New connect keys can now be created.
> feat(indexd): create key

- apps/explorer/tailwind.config.js
- apps/hostd/tailwind.config.js
- apps/indexd/tailwind.config.js
- apps/renterd/tailwind.config.js
- apps/walletd/tailwind.config.js
- libs/design-system/tailwind.config.js
- After recent upgrades I noticed that styles were not being compiled in dev mode.
- Discovered that the tailwind JIT no longer supports negative patterns inside the glob list.
> fix(tailwind): jit detects changes

- .changeset/slick-heads-trade.md
- .changeset/some-papers-agree.md
- apps/indexd/components/Metrics/index.tsx
- libs/indexd-types/src/admin/index.ts
- Renamed sectors metrics to slabs.
> fix(indexd): rename sector metric

- .changeset/gentle-llamas-cry.md
- .changeset/green-keys-peel.md
- .changeset/hip-ravens-pull.md
- .changeset/thin-buses-fetch.md
- apps/indexd/components/Data/Accounts/SidePanelAccountList.tsx
- apps/indexd/components/Data/Contracts/SidePanelContractList.tsx
- apps/indexd/components/Data/SidePanel.tsx
- apps/indexd/components/FilterMenu.tsx
- apps/indexd/components/Metrics/MetricsAccounts.tsx
- apps/indexd/components/Metrics/MetricsContracts.tsx
- apps/indexd/components/Metrics/MetricsSectors.tsx
- apps/indexd/components/Metrics/index.tsx
- libs/indexd-js/src/admin.ts
- libs/indexd-react/src/admin.ts
- libs/indexd-types/src/admin/index.ts
- Updated the sector stats key names.
- Added contract and account metrics to data panels.
- Added contract stats to metrics page.
> fix(indexd): add contract stats and improve ui

- .changeset/little-seals-marry.md
- libs/design-system/src/app/WalletBalanceEvolution.tsx
- libs/design-system/src/components/ChartXY/ChartXYGraph.tsx
> fix(design-system): wallet balance evolution y-axis values
