- .changeset/late-shirts-hug.md
- apps/renterd/components/Autopilot/index.tsx
- apps/renterd/components/Autopilot/useSyncContractSet.tsx
- libs/design-system/src/data/webLinks.ts
- Fixed an issue with automatically updating the default contract set when configuring autopilot before setting the default contract set. https://github.com/SiaFoundation/renterd/issues/503
> fix sync contractset autopilot config

- .changeset/few-pans-pump.md
- .changeset/giant-lamps-accept.md
- .changeset/metal-poems-smoke.md
- .changeset/serious-poems-drum.md
- .changeset/sour-pugs-fetch.md
- .changeset/weak-books-exercise.md
- apps/hostd/contexts/contracts/columns.tsx
- apps/renterd/components/Config/fields.tsx
- apps/renterd/components/Config/index.tsx
- apps/renterd/components/Config/transform.spec.ts
- apps/renterd/components/Config/transform.ts
- apps/renterd/components/Files/FilesStatsMenu/FilesStatsMenuHealth.tsx
- apps/renterd/components/Files/FilesStatsMenu/FilesStatsMenuSize.tsx
- apps/renterd/components/Hosts/StateEmpty.tsx
- apps/renterd/components/Hosts/index.tsx
- apps/renterd/components/RenterdAuthedLayout.tsx
- apps/renterd/components/Wallet/index.tsx
- apps/renterd/contexts/hosts/columns.tsx
- apps/renterd/contexts/hosts/dataset.ts
- apps/renterd/contexts/hosts/index.tsx
- apps/renterd/hooks/useUploadPackingSettings.tsx
- libs/design-system/src/components/Table.tsx
- libs/design-system/src/config/theme.js
- libs/react-renterd/src/autopilot.ts
- libs/react-renterd/src/bus.ts
- libs/react-renterd/src/siaTypes.ts
- Fixed a crash issue when loading the hosts explorer.
- The host explorer now works before autopilot is configured, the table shows the autopilot columns with empty values and tooltips explaining that autopilot is not configured.
- Upload packing can now be enabled from the configuration tab.
- Wallet balance is now more accurately calculated as spendable + unconfirmed.
- The contracts table now has an egress usage column. https://github.com/SiaFoundation/hostd/issues/143
> renterd upload packing, host explorer fix, host egress usage

- .changeset/calm-chairs-flash.md
- .changeset/hip-ravens-happen.md
- .changeset/serious-dots-occur.md
- .changeset/shaggy-dodos-heal.md
- .changeset/silly-bobcats-reflect.md
- .changeset/six-mugs-march.md
- .changeset/twenty-colts-type.md
- .changeset/wild-elephants-watch.md
- apps/renterd/components/Files/FilesStatsMenu/index.tsx
- apps/renterd/components/OnboardingBar.tsx
- apps/renterd/contexts/config/index.tsx
- apps/renterd/contexts/files/dataset.tsx
- apps/renterd/contexts/files/index.tsx
- apps/renterd/contexts/hosts/columns.tsx
- apps/renterd/contexts/hosts/dataset.ts
- apps/renterd/contexts/hosts/types.tsx
- libs/design-system/src/core/NumberField.tsx
- libs/design-system/src/core/SiacoinField.tsx
- libs/design-system/src/form/ConfigurationNumber.tsx
- libs/design-system/src/form/ConfigurationSiacoin.tsx
- libs/react-renterd/src/autopilot.ts
- libs/react-renterd/src/bus.ts
- libs/react-renterd/src/siaTypes.ts
- Hosts last scan column now properly displays unscanned values rather than a very large time ago value.
- Siacoin and number input placeholders now match the suggested value.
- The autopilot loop is now triggered after settings are successfully updated.
- Files are now paginated.
- Removed and updated deprecated route names.
- Onboarding fund wallet step now requires >0 SC instead of a full allowance.
- The hosts table now has a last announcement column instead of the known since column.
> renterd improvements

- .changeset/rude-suits-do.md
- apps/website/components/CalloutCoreSoftware.tsx
- apps/website/components/DownloadBar.tsx
- apps/website/components/DownloadSelect.tsx
- apps/website/pages/host/index.tsx
- apps/website/pages/rent/index.tsx
- apps/website/pages/software/hostd.tsx
- apps/website/pages/software/renterd.tsx
- apps/website/pages/software/walletd.tsx
- apps/website/pages/wallet/index.tsx
- libs/design-system/src/data/webLinks.ts
- Downloads are now more prominent on both use-case and software pages, and the correct OS is preselected. https://github.com/SiaFoundation/web/issues/406
> fix: website downloads

- .changeset/cool-beds-hunt.md
- .changeset/dull-birds-push.md
- .changeset/swift-kiwis-clean.md
- apps/hostd/components/Home/HomeOperations.tsx
- apps/hostd/components/Home/HomeRevenue.tsx
- apps/hostd/components/Home/HomeStorage.tsx
- apps/hostd/contexts/metrics/index.tsx
- apps/hostd/contexts/metrics/types.tsx
- Revenue metrics no longer show negative potential on the bar graph.
- Metrics no longer include registry related data.
- Earned revenue stat cards are now clearly labeled as earned.
> fix: hostd metrics min zero, remove registry

- .changeset/grumpy-bags-smell.md
- apps/renterd/components/Wallet/WalletFilterBar.tsx
- apps/renterd/components/Wallet/index.tsx
- apps/renterd/config/providers.tsx
- apps/renterd/contexts/transactions/index.tsx
- libs/react-renterd/src/bus.ts
- Wallet transactions are now paginated.
> renterd paginate transactions

- .changeset/little-drinks-work.md
- .changeset/rude-ways-hang.md
- apps/renterd/contexts/files/dataset.tsx
- apps/renterd/contexts/files/index.tsx
- apps/renterd/contexts/files/types.ts
- libs/design-system/src/hooks/useSorting.ts
- libs/design-system/src/hooks/useTableState.ts
- libs/react-renterd/src/bus.ts
- Files can now be sorted by name and health, ascending or descending.
> renterd file sorting

- .changeset/poor-ladybugs-protect.md
- .changeset/short-fishes-beg.md
- .changeset/slow-dancers-fold.md
- .changeset/smooth-tables-wink.md
- .changeset/sweet-pillows-join.md
- apps/renterd/components/Files/EmptyState/StateNoneMatching.tsx
- apps/renterd/components/Files/EmptyState/StateNoneYet.tsx
- apps/renterd/components/Files/FileContextMenu/index.tsx
- apps/renterd/components/Files/FilesCmd/FilesSearchCmd/index.tsx
- apps/renterd/components/Files/FilesFilterDirectoryMenu/index.tsx
- apps/renterd/components/Files/FilesSearchDialog/index.tsx
- apps/renterd/components/Files/FilesStatsMenu/FilesStatsMenuWarnings.tsx
- apps/renterd/components/Files/FilesStatsMenu/index.tsx
- apps/renterd/contexts/files/dataset.tsx
- apps/renterd/contexts/files/index.tsx
- libs/design-system/src/hooks/useServerFilters.ts
- libs/react-renterd/src/bus.ts
- Files in the current directory can now be filtered.
- Selecting a file search result now navigates to the directory and applies a file name filter.
- File warnings are now a simple warning icon next to the stats and are explained in a popover.
- The bucket empty state now has a button for navigating back to the buckets list.
> renterd filter files

- .changeset/old-tomatoes-divide.md
- .changeset/spicy-colts-glow.md
- .changeset/swift-apples-allow.md
- .changeset/swift-tools-remain.md
- .changeset/tender-peaches-breathe.md
- .changeset/witty-peaches-help.md
- apps/explorer/components/Faucet/FaucetFundForm.tsx
- apps/renterd/components/Contracts/ContractMetrics.tsx
- apps/renterd/components/Contracts/ContractsActionsMenu.tsx
- apps/renterd/components/Contracts/StateNoData.tsx
- apps/renterd/components/Files/Columns/FilesHealthColumn/FilesHealthColumnContents.tsx
- apps/renterd/contexts/contracts/index.tsx
- apps/renterd/contexts/contracts/types.ts
- apps/renterd/contexts/contracts/useContractMetrics.tsx
- apps/renterd/contexts/contracts/useContractSetMetrics.tsx
- apps/renterd/contexts/contracts/utils.ts
- apps/renterd/dialogs/AlertsDialog.tsx
- libs/design-system/src/app/AlertsDialog/index.tsx
- libs/design-system/src/components/ChartXY/index.tsx
- libs/react-renterd/src/bus.ts
- libs/react-renterd/src/siaTypes.ts
- The contracts feature now includes a graph of aggregate funding and spending across all active contracts.
- The contracts feature now includes a contract count graph for the autopilot contract set.
- The alerts dialog now has an "all" filter. https://github.com/SiaFoundation/hostd/issues/197
- Fixed an issue with the file health popover and updated it to display more accurate information. https://github.com/SiaFoundation/renterd/issues/804
- Updated the object partial slab response structure.
- The faucet validation now allows up to 50,000 SC.
> renterd aggregate contract stats, partial slab heath, alerts all filter, faucet limit

- .changeset/neat-mayflies-remember.md
- .changeset/tidy-zebras-exist.md
- .changeset/witty-dryers-camp.md
- apps/renterd/components/Contracts/index.tsx
- apps/renterd/components/Hosts/HostContextMenu.tsx
- apps/renterd/contexts/config/fields.tsx
- libs/design-system/src/core/InfoTip.tsx
- The host context menu now has options for copying public key or address to clipboard.
- The redundancy tooltip now correctly describes the ratio as total shards / min shards. https://github.com/SiaFoundation/renterd/issues/810
- Fixed an issue with the prune sector roots setting validation.  https://github.com/SiaFoundation/renterd/issues/812
> renterd host context menu copy, redundancy tooltip, prune validation, refine contract graph

- .changeset/happy-mirrors-do.md
- libs/design-system/src/app/WalletBalance.tsx
- libs/design-system/src/components/Form.tsx
The wallet balance shown on the wallet page is now spendable plus unconfirmed, just like the sidebar.
> fix wallet balance calculations

- .changeset/blue-eels-shake.md
- .changeset/bright-chicken-live.md
- .changeset/dull-trainers-rescue.md
- .changeset/funny-socks-kiss.md
- .changeset/happy-mirrors-do.md
- .changeset/sharp-countries-lick.md
- .changeset/soft-pianos-boil.md
- .changeset/tough-chairs-sit.md
- apps/hostd/components/Config/AnnounceButton.tsx
- apps/hostd/contexts/metrics/index.tsx
- apps/renterd/contexts/config/index.tsx
- apps/renterd/contexts/config/transform.spec.ts
- apps/renterd/contexts/config/transform.ts
- apps/renterd/contexts/config/types.ts
- apps/renterd/contexts/config/useAverages.tsx
- apps/renterd/contexts/config/useEstimates.tsx
- apps/renterd/contexts/config/useForm.tsx
- apps/renterd/contexts/config/useOnValid.tsx
- apps/renterd/contexts/config/useResources.tsx
- apps/renterd/contexts/contracts/useContractMetrics.tsx
- libs/design-system/src/app/WalletBalance.tsx
- libs/design-system/src/components/ChartXY/useChartXY.tsx
- libs/design-system/src/components/Form.tsx
- libs/design-system/src/form/useServerSyncedForm.tsx
- libs/design-system/src/index.ts
- libs/react-core/src/useAppSettings/index.tsx
- libs/react-hostd/src/api.ts
- Fix bug where announcement error shows both a success and error toast.
- Data metrics no longer use RHP version specific data.
- The wallet balance shown on the wallet page is now spendable plus unconfirmed.
- The contract funding and spending graph now shows a data point for brand new contracts.
- The default suggested pricing for new users is now based on Sia Central averages.
- Fixed an issue where currency was displayed with too many decimals.
- Added useServerSyncedForm.
- ChartXY no longer adds padding point for barstack and bargroup.
> renterd contract graphs, suggested pricing, balances, host data metrics, other bugs

- .changeset/early-otters-pretend.md
- .changeset/many-planes-shout.md
- apps/renterd/components/Files/FilesStatsMenu/FilesStatsMenuCount.tsx
- The total file count now includes in-progress uploads.
- The renterd file count stats tooltip description is now more accurate.
> renterd total file count fixes

- .changeset/funny-lions-deliver.md
- apps/hostd/contexts/metrics/useNowAtInterval.tsx
- apps/renterd/hooks/useS3AuthenticationSettings.tsx
- libs/design-system/src/components/ChartXY/ChartXYGraph.tsx
- libs/react-renterd/src/siaTypes.ts
- Fixed an issue where the app would not navigate when the metrics data interval was set to ALL.
> fix: hostd navigation bug

- .changeset/cool-walls-jam.md
- .changeset/stale-ties-yell.md
- .changeset/tricky-brooms-drive.md
- .changeset/twenty-seals-allow.md
- .eslintignore
- apps/hostd/contexts/config/useOnValid.tsx
- apps/renterd/components/Files/FilesStatsMenu/FilesStatsMenuHealth.tsx
- apps/website/config/mdx.tsx
- apps/website/pages/roadmap/index.tsx
- apps/website/project.json
- The file stats now only show health once there is more than 0 bytes of file data.
- Fixed an error with "lastAnnouncement" that occurs the first time the configuration is saved.
> renterd hide 0 file health, hostd fix configuration save error, other changes

- .changeset/wild-plums-guess.md
- apps/explorer/app/host/[id]/opengraph-image.tsx
- apps/explorer/components/Home/HostListItem.tsx
- apps/explorer/components/Home/index.tsx
- apps/explorer/components/Host/HostHeader.tsx
- apps/explorer/components/Host/HostInfo.tsx
- apps/explorer/components/Host/HostPricing.tsx
- apps/explorer/components/Host/HostSettings.tsx
- apps/explorer/components/Host/index.tsx
- apps/explorer/components/Host/types.ts
- apps/explorer/tsconfig.json
- libs/sia-central/src/types.tsx
- libs/units/src/storage.ts
- Fixed an error where looking up a host was showing an error page for unscanned hosts.
> fix: explorer host unscanned error

- .changeset/good-flies-doubt.md
- .changeset/healthy-cars-cover.md
- .changeset/pretty-hats-count.md
- apps/renterd/contexts/files/types.ts
- apps/renterd/contexts/files/uploads.tsx
- libs/react-renterd/src/bus.ts
- Uploading nested directories now preserves structure rather than flattening files into current directory.
- Files can now be sorted by size.
> renterd nested directory uploads, sort files by size

- .changeset/happy-ads-matter.md
- .changeset/red-vans-relate.md
- apps/renterd/components/Hosts/HostContextMenu.tsx
- libs/react-renterd/src/bus.ts
- The host context menu now has an option to reset the lost sector count.
> renterd reset lost sector count

- .changeset/new-suns-rush.md
- .changeset/tough-llamas-do.md
- apps/hostd/config/swr.ts
- apps/hostd/contexts/contracts/index.tsx
- apps/hostd/contexts/metrics/index.tsx
- apps/hostd/contexts/transactions/index.tsx
- apps/hostd/contexts/volumes/index.tsx
- apps/hostd/dialogs/AlertsDialog.tsx
- apps/renterd/config/swr.ts
- apps/renterd/contexts/contracts/index.tsx
- apps/renterd/contexts/filesDirectory/dataset.tsx
- apps/renterd/contexts/filesFlat/dataset.tsx
- apps/renterd/contexts/hosts/index.tsx
- apps/renterd/contexts/keys/index.tsx
- apps/renterd/contexts/transactions/index.tsx
- apps/renterd/dialogs/AlertsDialog.tsx
- apps/walletd/config/swr.ts
- apps/walletd/contexts/addresses/index.tsx
- apps/walletd/contexts/events/index.tsx
- apps/walletd/contexts/wallets/index.tsx
- apps/walletd/hooks/useWalletAddresses.tsx
- Integrity check alert sector data will now update when there is an ongoing integrity check.
- All data will now refresh more frequently.
> hostd integrity check sector data and general dataset refresh intervals

- .changeset/gentle-coats-camp.md
- .changeset/hip-ducks-occur.md
- .changeset/wicked-sloths-breathe.md
- apps/hostd/components/Profile/index.tsx
- apps/renterd/components/Profile/index.tsx
- libs/units/src/humanUnits.spec.ts
- libs/units/src/humanUnits.ts
- The renterd and hostd node profile details now include uptime.
> add net address and uptime to node profile

- .changeset/rare-pots-joke.md
- libs/design-system/src/app/ContractTimeline/Labels.tsx
- The contract timeline labels have been darkened to increase contrast and readability.
> contract timeline label contrast

- apps/website/components/Layout/Footer.tsx
- nx.json
CI lint configuration was switched to a warning during an NX version migration, this makes it strict again.
> chore: strict lint configuration for ci

- .changeset/flat-peas-enjoy.md
- .changeset/rotten-kangaroos-train.md
- apps/explorer/app/manifest.ts
- apps/explorer/app/opengraph-image.tsx
- apps/explorer/app/page.tsx
- libs/design-system/src/components/Table/TableRow.tsx
- libs/design-system/src/components/Table/index.tsx
- Update title and description on manifest, og images, and generated metadata.
Looking to fill out and improve the copy in search results:
> fix: explorer metadata

- .changeset/cold-fireants-flash.md
- apps/hostd/components/Home/HomeBandwidth.tsx
- apps/hostd/components/Home/HomeContracts.tsx
- apps/hostd/components/Home/HomeOperations.tsx
- apps/hostd/components/Home/HomeStorage.tsx
- libs/design-system/src/app/DatumCardConfigurable.tsx
- libs/design-system/src/components/DatumCard.tsx
- Siacoin metric cards now show the dynamic units with two decimal places.
> fix: hostd metrics data add decimals

- .changeset/mighty-ghosts-drive.md
- .changeset/small-apricots-sort.md
- apps/hostd/components/Home/HomeBandwidth.tsx
- apps/hostd/components/Home/HomeCollateral.tsx
- apps/hostd/components/Home/HomeContracts.tsx
- apps/hostd/components/Home/HomeOperations.tsx
- apps/hostd/components/Home/HomePricing.tsx
- apps/hostd/components/Home/HomeRevenue.tsx
- apps/hostd/components/Home/HomeStorage.tsx
- apps/renterd/components/Contracts/ContractMetrics.tsx
- libs/design-system/src/app/WalletBalanceEvolution.tsx
- libs/design-system/src/components/ChartXY/useChartXY.tsx
- All graphs now remember any chart configuration that the user has selected.
> fix: apps remember user chart configuration

- .changeset/rotten-kangaroos-train.md
- .changeset/stupid-fishes-brake.md
- .changeset/weak-tips-raise.md
- apps/explorer/components/Contract/index.tsx
- apps/explorer/components/ExplorerDatum.tsx
- libs/design-system/src/components/EntityListItem.tsx
- libs/design-system/src/components/Table/TableRow.tsx
- libs/design-system/src/components/Table/index.tsx
- Add detailed labels to contract proof outputs explaining what each output is for.
> fix: explorer proof output labels

- apps/renterd/lib/multipartUpload.spec.ts
- apps/renterd/lib/multipartUpload.ts
- libs/react-renterd/src/worker.ts
- Multipart uploader class, for use within renterd's upload manager.
- Supports configurable chunk sizes and concurrent chunks.
- Reports combined total progress from across all concurrent requests.
- Recovers from failed chunks with increasing backoff until success.
- Supports aborting entire multipart upload.
> feat: renterd multipart uploader

- .changeset/empty-garlics-look.md
- .changeset/pretty-roses-develop.md
- apps/renterd/components/TransfersBar.tsx
- apps/renterd/contexts/filesManager/index.tsx
- apps/renterd/contexts/filesManager/types.ts
- apps/renterd/contexts/filesManager/uploads.tsx
- apps/renterd/lib/paths.ts
- libs/react-renterd/src/siaTypes.ts
- server/Caddyfile-dev
- File uploads now use multipart uploads.
- File uploads now have a max concurrency and get queued.
- Uploads in the transfers list report aggregate progress from across chunks.
- The browser now warns the user if they have active uploads and try to close the tab.
> feat: renterd multipart upload manager

- .changeset/friendly-nails-marry.md
- apps/renterd/contexts/filesManager/uploads.tsx
- apps/renterd/contexts/filesManager/useWarnActiveUploadsOnClose.tsx
- The browser now warns the user if they have active uploads and try to close the tab.
> feat: renterd warn active uploads

- apps/renterd/contexts/alerts/data.tsx
- Two data fields were using 14 instead of 12.
> fix: renterd alerts data text size

- .changeset/violet-starfishes-swim.md
- .changeset/wise-eagles-allow.md
- apps/renterd/contexts/alerts/columns.tsx
- apps/renterd/contexts/alerts/data.tsx
- apps/renterd/contexts/alerts/index.tsx
- Fixed an issue where the alert data fields showed the wrong dates.
- Fixed an issue where the alert columns were not initially showing.
> fix: renterd alerts relative time and column state

- .changeset/tricky-tables-know.md
- apps/renterd/lib/multipartUpload.spec.ts
- apps/renterd/lib/multipartUpload.ts
- Uploads will now error and abort if responses are missing etags.
> fix: renterd multipart etag error

- .changeset/few-chefs-love.md
- .changeset/large-crews-play.md
- .changeset/rich-lemons-speak.md
- apps/renterd/components/Uploads/UploadsStatsMenu/index.tsx
- apps/renterd/contexts/filesDirectory/columns.tsx
- apps/renterd/contexts/filesDirectory/dataset.tsx
- apps/renterd/contexts/filesFlat/columns.tsx
- apps/renterd/contexts/filesFlat/dataset.tsx
- apps/renterd/contexts/filesManager/dataset.tsx
- apps/renterd/contexts/filesManager/uploads.tsx
- apps/renterd/contexts/uploads/index.tsx
- apps/renterd/lib/multipartUpload.spec.ts
- apps/renterd/lib/multipartUpload.ts
- Fixed a slow memory leak that became especially apparent during long running large uploads, memory usage is now minimal and stable over time.
- Uploads now support aborting the entire visible page of active uploads.
- Directory and global file explorers now show upload progress inline.
> fix: renterd memory leak, abort uploads, inline progress

- .changeset/clean-icons-divide.md
- apps/explorer/app/host-revenue-calculator/error.tsx
- apps/explorer/app/host-revenue-calculator/not-found.tsx
- apps/explorer/app/host-revenue-calculator/opengraph-image.tsx
- apps/explorer/app/host-revenue-calculator/page.tsx
- apps/explorer/components/Layout/NavDropdownMenu.tsx
- apps/explorer/config/routes.ts
- The explorer now features a host revenue calculator tool.
> feat: explorer host revenue calculator

- .changeset/real-carrots-cry.md
- apps/walletd/hooks/useSyncStatus.ts
- apps/walletd/lib/signSeed.ts
- libs/react-walletd/src/api.ts
- libs/react-walletd/src/siaTypes.ts
- libs/sdk/README.md
- libs/sdk/package.json
- libs/sdk/src/sdk.ts
- libs/sdk/src/types.ts
- libs/sdk/src/wallet.mock.ts
- libs/sdk/src/wallet.spec.ts
- libs/types/src/index.ts
- sdk/main.go
- sdk/wallet.go
- Wallet and transaction signing methods are now part of the sdk.
> refactor: migrate wallet wasm into sdk

- apps/renterd/contexts/alerts/SetChange.tsx
- Sort contracts by desc size
- Sort the contract's changes by desc date
- Relative time display
- Churn % displayed at the top
- Number of additionals/removals displayed at the top
- Full background color and contrast only on the most recent change
> renterd contract set change alert details

- .changeset/fast-suits-punch.md
- .changeset/honest-falcons-rhyme.md
- .github/workflows/pr.yml
- .github/workflows/release-main.yml
- apps/walletd-e2e/project.json
- apps/walletd/config/providers.tsx
- apps/walletd/contexts/app/index.tsx
- apps/walletd/project.json
- libs/sdk/project.json
- libs/sdk/src/index.ts
- libs/sdk/src/sdk.ts
- libs/sdk/src/transport.ts
- libs/sdk/src/types.ts
- libs/sdk/src/wallet.spec.ts
- libs/sdk/src/wasm.ts
- libs/types/src/core.ts
- sdk/main.go
- sdk/wallet.go
- tsconfig.base.json
> This PR cleans up the SDK and sets it up in the walletd app.
- Clean up SDK API, WebTransportClient parameters, tweaks
- Fix signTransaction and update to signTransactionV1
- Add basic SDK initialization to walletd
> SDK cleanup, set up SDK in walletd

- .github/workflows/release-go.yml
- .github/workflows/release-main.yml
- Move to push rather than polling
- Use the repository dispatch action
- Removed the likely unnecessary COMMIT_PAT from repo
> ci: use repository dispatch

- .changeset/forty-toes-reflect.md
- .changeset/many-panthers-wonder.md
- apps/walletd/components/Profile/index.tsx
- libs/react-walletd/src/api.ts
- The profile details now include uptime and version.
> feat: walletd state information

- .changeset/slow-ties-admire.md
- libs/react-core/package.json
- libs/react-core/src/request.ts
- libs/react-core/src/useDelete.ts
- libs/react-core/src/useGet.ts
- libs/react-core/src/usePatch.ts
- libs/react-core/src/usePost.ts
- libs/react-core/src/usePut.ts
- libs/request/.babelrc
- libs/request/.eslintrc.json
- libs/request/README.md
- libs/request/jest.config.ts
- libs/request/package.json
- libs/request/project.json
- libs/request/rollup.config.js
- libs/request/src/index.ts
- libs/request/tsconfig.json
- libs/request/tsconfig.lib.json
- libs/request/tsconfig.spec.json
- tsconfig.base.json
This PR creates a `request` library and extracts shared request/network code from `react-core` that is not react-specific. This code is for use in `renterd-js` and others for API methods.
> refactor: split out a requests library

- apps/renterd/config/routes.ts
- apps/renterd/contexts/config/useOnValid.tsx
- apps/renterd/contexts/hosts/columns.tsx
- libs/react-core/package.json
- libs/renterd-react/src/autopilot.ts
- libs/renterd-react/src/bus.ts
- libs/renterd-react/src/worker.ts
- libs/renterd-types/src/autopilot.ts
- libs/renterd-types/src/bus.ts
- libs/renterd-types/src/worker.ts
This PR moves all renterd API route strings to shared constants that can be used across libraries. This makes updating all libraries at once easier and also avoids small string typos.
These strings are used for API routes and also data revalidation in react mutations and hooks.
> refactor: renterd libs extract route variables

- .changeset/calm-sloths-collect.md
- libs/renterd-js/.babelrc
- libs/renterd-js/.eslintrc.json
- libs/renterd-js/README.md
- libs/renterd-js/jest.config.ts
- libs/renterd-js/package.json
- libs/renterd-js/project.json
- libs/renterd-js/rollup.config.js
- libs/renterd-js/src/autopilot.ts
- libs/renterd-js/src/bus.ts
- libs/renterd-js/src/example.ts
- libs/renterd-js/src/index.ts
- libs/renterd-js/src/worker.ts
- libs/renterd-js/tsconfig.json
- libs/renterd-js/tsconfig.lib.json
- libs/renterd-js/tsconfig.spec.json
- libs/request/src/index.ts
- tsconfig.base.json
This PR adds a `renterd-js` library.
```sh
npm install @siafoundation/renterd-js
```
```js
import { Bus } from './bus'
import { Autopilot } from './autopilot'
import { Worker } from './worker'
export async function example() {
const bus = Bus({
api: 'http://localhost:9980',
password: 'password1337',
})
const autopilot = Autopilot({
api: 'http://localhost:9980',
password: 'password1337',
})
const worker = Worker({
api: 'http://worker:4444',
password: 'password1337',
})
const buckets = await bus.buckets()
buckets.data.forEach((bucket) => {
console.log(bucket.name, bucket.createdAt, bucket.policy)
})
bus.bucketCreate({
data: { name: 'my-bucket' },
})
bus.bucketPolicyUpdate({
params: {
name: 'my-bucket',
},
data: {
policy: {
publicReadAccess: true,
},
},
})
const hosts = await …
```
> feat: renterd-js library

- .changeset/nervous-timers-float.md
- libs/design-system/package.json
- libs/fonts/package.json
Moves everything besides `react` and `next` out of peer dependencies. This makes consuming the libraries a bit easier when using other package managers like `yarn` that require manually installing peers.
> refactor: peer dependencies

- .changeset/large-buckets-talk.md
- apps/renterd/contexts/config/fields.tsx
- apps/renterd/contexts/config/transform.spec.ts
- apps/renterd/contexts/config/transform.ts
- apps/renterd/contexts/config/types.ts
- libs/renterd-types/src/types.ts
- The configuration now includes the min protocol version option.
- The value is automatically set to 1.6.0 for new users when using the simple configuration mode.
- Input field validates that value is a version string with 3 numeric segments, eg 1.6.11.
> feat: renterd min protocol version

- .changeset/gentle-onions-report.md
- libs/renterd-types/src/worker.ts
- `File` is only supported in browsers, widening these upload types to accept other data.
> fix: renterd-js objectUpload support more data types

- hostd/hostd_test.go
- internal/nextjs/nextjs.go
- renterd/renterd_test.go
- walletd/walletd_test.go
Switches the nextjs Go router to use `path` instead of `filepath` to prevent issues on Windows. Also adds a few sanity tests to make sure the routers initialize correctly.
> Use path instead of filepath for UI assets

- .changeset/red-wasps-push.md
- .gitattributes
- .github/actions/setup-all/action.yml
- .github/actions/setup-git/action.yml
- .github/actions/setup-go/action.yml
- .github/actions/setup-js/action.yml
- .github/workflows/pr.yml
- .github/workflows/release-go.yml
- .github/workflows/release-main.yml
- Lint passed on windows with both:
- `git config --global core.autocrlf false`
- `.gitattributes`: `*.go text eol=lf`
> fix: embedded ui handler panic, go test matrix, refactor workflows

- .changeset/fluffy-horses-turn.md
- apps/renterd/components/Files/Columns/FilesHealthColumn/FilesHealthColumnContents.tsx
- Fixed an issue where file health slab keys were showing up as repeated and incorrect.
> fix: renterd file health slab keys

- .github/workflows/release-main.yml
- 8 min - Moves JS linting, testing, e2e testing out to a parallel job
- 3 min - Moves docker container build and publish out to a parallel job
> ci: speed up release workflow by 2x

- .changeset/smart-papayas-do.md
- apps/hostd/contexts/dialog.tsx
- apps/hostd/dialogs/VolumeResizeDialog.tsx
- Fixed an issue where volume resize and delete dialogs were not loading the volumes data.
- Updated volume resize dialog to used shared helpers for consistency.
**Explanation**
- Recently fixed an issue where dialogs were not triggering onOpenChange(true) when initially opening, this combined with an incorrect handler that previously never was called caused the `id` passed to volume dialogs to get wiped out.
> fix: hostd volume resize and delete dialogs

- .changeset/fast-colts-turn.md
- .changeset/old-candles-remember.md
- .changeset/proud-dancers-train.md
- apps/renterd/components/Config/Recommendations.tsx
- apps/renterd/contexts/config/useAutopilotEvaluations.tsx
- apps/renterd/contexts/config/useForm.tsx
- Fixed an issue where clearing some configuration fields would crash the app due to how recommendations were being calculated.
- The configuration recommendations now instruct the user to first fill all fields.
- Fixed an issue where the recommendations bar was overlapping notifications.
> fix: renterd recommendations states and crashing

- .changeset/gentle-zoos-love.md
- .changeset/six-fishes-check.md
- apps/walletd/contexts/events/columns.tsx
- apps/walletd/contexts/events/index.tsx
- apps/walletd/contexts/events/types.ts
- libs/design-system/src/components/Table/TableRow.tsx
- libs/design-system/src/core/Separator.tsx
- libs/walletd-types/src/types.ts
- Updated wallet events to include maturityHeight and renamed val to data.
- The events list now shows the maturity height, transactions that have not reached this height are shown as locked.
> walletd maturity height, walletd events update

- .changeset/tender-plants-live.md
- apps/walletd/contexts/events/index.tsx
- Unconfirmed transactions rows now show their siacoin amount and fees.
> fix: walletd pending transaction sc amount

- .changeset/lovely-teachers-move.md
- .changeset/tender-pants-decide.md
- apps/hostd-e2e/src/fixtures/login.ts
- apps/hostd-e2e/src/fixtures/navigateToConfig.ts
- apps/hostd-e2e/src/fixtures/navigateToDashboard.ts
- apps/hostd-e2e/src/specs/login.spec.ts
- apps/renterd-e2e/src/fixtures/buckets.ts
- apps/renterd-e2e/src/fixtures/login.ts
- apps/renterd-e2e/src/fixtures/navigateToBuckets.ts
- apps/renterd-e2e/src/fixtures/navigateToConfig.ts
- apps/renterd-e2e/src/specs/buckets.spec.ts
- apps/renterd-e2e/src/specs/login.spec.ts
- apps/renterd/components/Files/BucketContextMenu.tsx
- apps/renterd/contexts/config/useAutopilotEvaluations.tsx
- apps/renterd/contexts/config/useForm.tsx
- apps/renterd/contexts/dialog.tsx
- apps/walletd-e2e/src/fixtures/login.ts
- libs/design-system/src/app/AppNavbar.tsx
- Fixed an issue where selecting a bucket context menu option would also navigate into the bucket. https://github.com/SiaFoundation/renterd/issues/1277
- Fixed an issue that broke some dialogs including the bucket policy and bucket delete dialogs. https://github.com/SiaFoundation/renterd/issues/1277
> fix: renterd dialogs, bucket policy, delete

- .changeset/few-bees-compete.md
- apps/hostd-e2e/src/fixtures/navigate.ts
- apps/hostd-e2e/src/fixtures/navigateToDashboard.ts
- apps/hostd-e2e/src/fixtures/volumes.ts
- apps/hostd-e2e/src/specs/config.spec.ts
- apps/hostd-e2e/src/specs/volumes.spec.ts
- apps/hostd/dialogs/VolumeCreateDialog.tsx
- apps/hostd/dialogs/VolumeDeleteDialog.tsx
- apps/renterd-e2e/src/fixtures/buckets.ts
- apps/renterd-e2e/src/fixtures/navigate.ts
- apps/renterd-e2e/src/fixtures/navigateToBuckets.ts
- apps/renterd-e2e/src/fixtures/navigateToConfig.ts
- apps/renterd-e2e/src/specs/buckets.spec.ts
- apps/renterd-e2e/src/specs/config.spec.ts
- Refined the volume deletion toast message to "Volume is now being permanently deleted". https://github.com/SiaFoundation/hostd/issues/409
> fix: hostd volume test and delete message

- .changeset/slow-buses-bake.md
- apps/hostd-e2e/src/fixtures/configResetAllSettings.ts
- apps/hostd-e2e/src/fixtures/switchValue.ts
- apps/hostd-e2e/src/fixtures/textInput.ts
- apps/hostd-e2e/src/fixtures/volumes.ts
- apps/hostd-e2e/src/specs/config.spec.ts
- apps/hostd/contexts/config/fields.tsx
- The pin max collateral switch is now visible in basic view mode. https://github.com/SiaFoundation/hostd/issues/417
> fix: hostd pin max collateral visible in basic view mode

- .changeset/gentle-countries-cry.md
- .changeset/hip-turkeys-remember.md
- .changeset/short-bears-grab.md
- apps/renterd-e2e/src/fixtures/beforeTest.ts
- apps/renterd-e2e/src/fixtures/buckets.ts
- apps/renterd-e2e/src/fixtures/configResetAllSettings.ts
- apps/renterd-e2e/src/fixtures/files.ts
- apps/renterd-e2e/src/fixtures/navigate.ts
- apps/renterd-e2e/src/specs/buckets.spec.ts
- apps/renterd-e2e/src/specs/config.spec.ts
- apps/renterd-e2e/src/specs/files.spec.ts
- apps/renterd-e2e/src/specs/sample.txt
- apps/renterd/components/Files/DirectoryContextMenu.tsx
- apps/renterd/components/Files/FileContextMenu/index.tsx
- apps/renterd/components/FilesDirectory/EmptyState/StateNoneYet.tsx
- apps/renterd/components/FilesDirectory/FilesActionsMenu.tsx
- apps/renterd/components/FilesDirectory/FilesExplorer.tsx
- apps/renterd/contexts/dialog.tsx
- apps/renterd/dialogs/FileRenameDialog.tsx
- apps/renterd/dialogs/FilesBucketDeleteDialog.tsx
- libs/design-system/src/app/AppAuthedLayout/Sidenav.tsx
- libs/design-system/src/components/Dropzone.tsx
- libs/design-system/src/components/Table/TableRow.tsx
- libs/design-system/src/components/Table/index.tsx
- libs/design-system/src/form/configurationFields.ts
- package-lock.json
- package.json
- Fixed an issue where renaming a file would throw an error.
- Fixed an issue where the empty directory state was showing an empty bucket message.
- Added e2e tests for:
- can create directory
- delete directory
- drag and drop target uploads
- upload file within directory
- rename file
- delete a file
- re-upload same file
- navigate up and down directories
- delete bucket with contents, contents first, then bucket
> fix: renterd file rename, add e2e tests

- .changeset/thin-doors-notice.md
- apps/explorer/components/Block/index.tsx
- apps/explorer/components/ExplorerDatum.tsx
- apps/explorer/lib/utils.ts
- libs/design-system/src/components/ValueCopyable.tsx
- libs/design-system/src/lib/entityTypes.ts
fixes #451 
Hello! I've been looking at this codebase for a couple of days now and saw a task I thought was approachable for a first PR. This change addresses the issue by modifying the following files:
1. `ExplorerDatum.tsx`
2. `ValueCopyable.tsx`
3. `Block/index.ts`
These are backward-compatible changes, as far as I know, given the optional nature of the props and how the text value in ValueCopyable is calculated.
Issue: `ValueCopyable`, via `ExplorerDatum`, displays the Block hash's first 12 characters, which are typically 0s, with a trailing ellipsis.
Solution: Display the last 12 characters instead, adding the ellipsis at the front. 
How: Add optional maxLength and ellipsisDir props to `ExplorerDatum`, pass them to `ValueCopyable` (adding the optional ellipsisDir prop here), and …
> Add block hash display case, using middle ellipsis, to ValueCopyable

- .changeset/clean-eggs-compare.md
- apps/walletd/contexts/events/index.tsx
- apps/walletd/contexts/events/utils.ts
- libs/walletd-types/src/types.ts
- Fixed a few inaccuracies in the event data types. https://github.com/SiaFoundation/walletd/issues/141
> fix: wallet event data types

- .changeset/dirty-dodos-wave.md
- .changeset/empty-jobs-accept.md
- .changeset/shy-fans-explode.md
- apps/renterd-e2e/src/fixtures/configResetAllSettings.ts
- apps/renterd-e2e/src/specs/config.spec.ts
- apps/renterd/contexts/config/derivePricesFromAllowance.spec.ts
- apps/renterd/contexts/config/derivePricesFromAllowance.ts
- apps/renterd/contexts/config/fields.tsx
- apps/renterd/contexts/config/index.tsx
- apps/renterd/contexts/config/transformUp.ts
- apps/renterd/contexts/config/useAutoCalculatedFields.tsx
- apps/renterd/contexts/config/useAutopilotEvaluations.tsx
- apps/renterd/contexts/config/useEstimates.tsx
- apps/renterd/contexts/config/useForm.tsx
Status: Ready for review
The PR adds a default option to automatically calculate max gouging prices from the user configured usage estimates and allowance.
I don't think the previous simpler `f(allowance, percents) => pricing` version really captured the intended behaviour so I expanded the equation to incorporate the user estimates, while proportionally fixing the prices according to configurable weights, default: 10% upload, 50% download, 40% storage. Let me know if this solution makes sense.
The `derivePricingFromAllowance` method calculates the max price per TB for storage, download, and upload given a total spending allowance and estimated usage in TB for each type. The prices are kept proportional to each other using the weight factors provided as parameters. Storage and upload are …
> refactor: renterd allowance derived max pricing

- libs/design-system/src/core/ScrollArea.tsx
This would fix [issue](https://github.com/SiaFoundation/hostd/issues/423)
The more elegant fix would be:
- create a invisible bar on top the actual scroll bar without the margin.
- and make current scroll bar unclickable, that should keep the visual the same - but would complicated code.
If you like this simple approach then please merge this. Thank you!
> fix: remove 1 px margin between in scroll bar holder and scroll bar

- .changeset/cool-spies-laugh.md
- Fixed an issue where scrollbars could not be grabbed by moving mouse to the edge of the screen. https://github.com/SiaFoundation/hostd/issues/423 Fixed by https://github.com/kocoten1992
> fix: scrollbar flush edge

- .changeset/fifty-hornets-begin.md
- apps/website/components/CalloutCoreSoftware.tsx
- apps/website/components/CalloutWalletd.tsx
- apps/website/components/DownloadSection.tsx
- apps/website/pages/host/index.tsx
- apps/website/pages/rent/index.tsx
- apps/website/pages/software/hostd.tsx
- apps/website/pages/software/renterd.tsx
- apps/website/pages/software/walletd.tsx
- apps/website/pages/wallet/index.tsx
- The testnet prefix label was removed from the walletd downloads. https://github.com/SiaFoundation/web/issues/667
> fix: website walletd testnet label

- .changeset/dry-schools-breathe.md
- .changeset/empty-boats-occur.md
- .changeset/quiet-numbers-tie.md
- apps/website/components/CalloutWalletd.tsx
- apps/website/components/SoftwareSectionCurrentGen.tsx
- apps/website/pages/software/walletd.tsx
- apps/website/pages/wallet/index.tsx
- Fixed the Sia-UI download links.
- Removed the beta badge for the walletd daemon.
- Removed siad from the website.
> fix: website sia-ui downloads

- .changeset/hip-trees-appear.md
- .changeset/stupid-peaches-brake.md
- apps/renterd/contexts/config/transform.spec.ts
- apps/renterd/contexts/config/transformDown.ts
- apps/renterd/contexts/config/transformUp.ts
- libs/renterd-types/src/types.ts
- Updated the pricepinning configuration structure to support multiple autopilots. https://github.com/SiaFoundation/renterd/issues/1448
- Fixed an issue where the pricepinning response was crashing the app. https://github.com/SiaFoundation/renterd/issues/1448
> fix: renterd pricepinning autopilot config structure

- .changeset/cyan-deers-wash.md
- .changeset/smart-crabs-play.md
- apps/renterd-e2e/src/fixtures/configResetAllSettings.ts
- apps/renterd/components/Config/index.tsx
- apps/renterd/contexts/config/fieldTips/MaxRPCPrice.tsx
- apps/renterd/contexts/config/fields.tsx
- apps/renterd/contexts/config/transform.spec.ts
- apps/renterd/contexts/config/transformDown.ts
- apps/renterd/contexts/config/transformUp.ts
- apps/renterd/contexts/config/types.ts
- apps/renterd/contexts/config/useAllowanceDerivedPricing.tsx
- apps/renterd/contexts/config/useAutopilotEvaluations.tsx
- libs/renterd-types/src/types.ts
- Fixed an issue where the UI would set extremely small pinned max price values because it set values in per byte instead of TB.
- Max RPC price is no longer pinnable.
> fix: renterd pinned field units

- .changeset/chilly-buttons-sell.md
- .changeset/shiny-phones-burn.md
- apps/hostd/contexts/config/types.ts
- apps/renterd-e2e/src/fixtures/beforeTest.ts
- apps/renterd-e2e/src/fixtures/preferences.ts
- apps/renterd-e2e/src/specs/config.spec.ts
- libs/design-system/package.json
- libs/design-system/src/app/CurrencyDisplaySelector.tsx
- libs/design-system/src/core/SiacoinField.tsx
- libs/design-system/src/form/ConfigurationFiat.tsx
- libs/design-system/src/form/FieldFiat.tsx
- libs/design-system/src/hooks/useExchangeRate.tsx
- libs/design-system/src/hooks/useSiacoinFiat.tsx
- libs/design-system/src/index.ts
- Fixed an issue where network averages shown on pinned field tips did not follow the currency display preference.
> fix: renterd pinned average display

- .changeset/spicy-clouds-deliver.md
- libs/explored-types/src/types.ts
In creating this PR: https://github.com/SiaFoundation/web/pull/698
I discovered a webpack-related warning for our import of core types in the `explored-types`. By doing:
```ts
import { Address, ... } from '@siafoundation/types'
```
this led to an avalanche of warnings like so:
```bash
export 'Address' (reexported as 'Address') was not found in '@siafoundation/types' (module has no exports)
```
By adding the 'type' at the top of `types.ts`:
```ts
import type { Address, ... } from '@siafoundation/types'
```
this warning no longer sounds. I believe this has to do with some bare metal typescript -> javascript transpilation + importing rules at the webpack level. There was no obvious bug/misbehavior as a result of the former implementation. The library worked, from what I tested, and types …
> fix: explored-types: add 'type' to core types import, silencing webpack empty export warning

- .changeset/lovely-clocks-juggle.md
- apps/explorer/config/explored.ts
- apps/explorer/config/index.ts
- apps/explorer/config/testnet-zen.ts
I figured this one conceptually made sense as its own little PR as opposed to tacking it onto the first phase out route PR and having it get lost in the history a bit.
The zen address is probably wrong here or there just isn't support for this yet. Should I remove that line or is there a current working address? Am I correct that we're using testnet-zen in a docker config to stand in for that local `index.ts` to switch between the different modes?
> add explored api sdk to config, for use in future siacentral phase out

- .changeset/short-lizards-shop.md
- libs/renterd-js/src/bus.ts
- libs/renterd-react/src/bus.ts
- libs/renterd-types/src/bus.ts
- Remove deprecated hosts API. Relates to https://github.com/SiaFoundation/renterd/pull/1484
> refactor: renterd remove deprecated hosts API

- .changeset/small-cameras-lay.md
- apps/renterd-e2e/src/specs/config.spec.ts
- apps/renterd/components/Config/Recommendations.tsx
- The recommendations now say "no recommendations" instead of 0. https://github.com/SiaFoundation/desktop/issues/90
> fix: renterd no recommendations

- .changeset/shiny-onions-unite.md
- .changeset/spicy-boats-sneeze.md
- .changeset/sweet-meals-flash.md
- apps/hostd/components/Home/HomeContracts.tsx
- apps/hostd/config/charts.ts
- apps/hostd/contexts/metrics/index.tsx
- apps/hostd/contexts/metrics/types.tsx
- apps/hostd/contexts/transactions/index.tsx
- libs/hostd-types/src/api.ts
- The metrics APIs now include wallet with balance and immatureBalance. https://github.com/SiaFoundation/hostd/issues/450
- The metrics API types now include all available fields.
- hostd: The contracts metrics now show active, rejected, failed, renewed, finalized, and successful.
> fix: hostd metrics

- .changeset/cold-trees-relate.md
- libs/renterd-js/src/bus.ts
- libs/renterd-js/src/worker.ts
- libs/renterd-react/src/bus.ts
- libs/renterd-react/src/worker.ts
- libs/renterd-types/src/bus.ts
- libs/renterd-types/src/worker.ts
- The account reset drift API was moved from bus to worker. https://github.com/SiaFoundation/web/issues/704
> refactor: renterd account reset drift moved to worker

- .changeset/moody-zebras-fly.md
- .changeset/shy-dots-complain.md
- .changeset/thick-rats-smell.md
- .changeset/young-gifts-return.md
- apps/hostd-e2e/src/fixtures/beforeTest.ts
- apps/hostd-e2e/src/fixtures/navigate.ts
- apps/hostd-e2e/src/fixtures/preferences.ts
- apps/hostd-e2e/src/fixtures/siascan.ts
- apps/hostd-e2e/src/specs/config.spec.ts
- apps/hostd-e2e/src/specs/volumes.spec.ts
- apps/hostd-e2e/src/specs/wallet.spec.ts
- apps/hostd/dialogs/HostdSendSiacoinDialog.tsx
- apps/renterd-e2e/src/fixtures/navigate.ts
- apps/renterd-e2e/src/specs/wallet.spec.ts
- apps/renterd/dialogs/RenterdSendSiacoinDialog.tsx
- libs/design-system/src/app/WalletLayoutActions.tsx
- libs/design-system/src/app/WalletSendSiacoinDialog/Complete.tsx
- libs/design-system/src/app/WalletSendSiacoinDialog/Confirm.tsx
- libs/design-system/src/app/WalletSendSiacoinDialog/Generate.tsx
- libs/design-system/src/app/WalletSendSiacoinDialog/Receipt.tsx
- libs/design-system/src/app/WalletSendSiacoinDialog/index.tsx
- libs/design-system/src/app/WalletSendSiacoinDialog/types.ts
- libs/design-system/src/app/WalletSendSiacoinDialog/utils.ts
- libs/design-system/src/components/ValueCopyable.tsx
- libs/design-system/src/components/ValueSc.tsx
- libs/hostd-types/src/api.ts
- libs/renterd-js/src/bus.ts
- libs/renterd-react/src/bus.ts
- libs/renterd-types/src/bus.ts
Blocked by https://github.com/SiaFoundation/hostd/issues/454
Relates to https://github.com/SiaFoundation/renterd/pull/1436
- The send siacoin feature now calculates the fee using the daemon's recommended fee and a standard transaction size.
- Add e2e tests for sending siacoin.
- Fixed the recommended fee API route.
- Added the wallet send API.
- The send siacoin feature now calculates the fee using the daemon's recommended fee and a standard transaction size.
- Add e2e tests for sending siacoin.
- Refactor test setup with `beforeTest` helper.
- The wallet send API now supports the subtractMinerFee option.
> feat: renterd hostd wallet send

- .changeset/chatty-actors-shop.md
- apps/renterd/components/Config/Recommendations.tsx
- libs/units/src/pluralize.spec.ts
- libs/units/src/pluralize.ts
- Fixed a bug in the pluralize helper, added tests.
> fix: pluralize add tests

- .changeset/beige-ducks-knock.md
- libs/explored-types/src/types.ts
Matching the change made here: https://github.com/SiaFoundation/explored/pull/75.
We made need to restart/redeploy the public explored build with the linked change in mind to fully unblock me on this.
> refactor: explored-types: add id to ExplorerTransaction type

- .github/actions/setup-all/action.yml
- .github/actions/setup-go/action.yml
- .github/workflows/pr.yml
- .github/workflows/release-go.yml
- .github/workflows/release-main.yml
- .gitignore
- apps/renterd-e2e/playwright.config.ts
- apps/renterd-e2e/project.json
- apps/renterd-e2e/src/fixtures/beforeTest.ts
- apps/renterd-e2e/src/fixtures/clusterd.ts
- apps/renterd-e2e/src/fixtures/configResetAllSettings.ts
- apps/renterd-e2e/src/fixtures/hosts.ts
- apps/renterd-e2e/src/fixtures/login.ts
- apps/renterd-e2e/src/fixtures/navigate.ts
- apps/renterd-e2e/src/specs/buckets.spec.ts
- apps/renterd-e2e/src/specs/config.spec.ts
- apps/renterd-e2e/src/specs/contracts.spec.ts
- apps/renterd-e2e/src/specs/files.spec.ts
- apps/renterd-e2e/src/specs/login.spec.ts
- apps/renterd-e2e/src/specs/recommendations.spec.ts
- apps/renterd/components/Hosts/index.tsx
- apps/renterd/components/OnboardingBar.tsx
- apps/renterd/contexts/hosts/columns.tsx
- hostd/go.mod
- renterd/go.mod
- sdk/go.mod
- walletd/go.mod
- Add support for clusterd testing.
- Migrate all renterd tests to clusterd.
- Testing is now parallel, worker count: half logical cpus locally, 2 workers on CI
- Re-enabled testing against all browsers.
- Updated all go versions to 1.23.0, to align with cluster deps.
> refactor: renterd tests cluster

- .github/workflows/release-main.yml
Since we don't have a `go.work` file any more, `go test` needs to use the package working directory. Should fix all this
> Use working directory instead of package for go test

- .vscode/spellright.dict
- README.md
- apps/renterd-e2e/src/fixtures/beforeTest.ts
- apps/renterd-e2e/src/specs/login.spec.ts
- libs/clusterd/.babelrc
- libs/clusterd/.eslintrc.json
- libs/clusterd/README.md
- libs/clusterd/jest.config.ts
- libs/clusterd/package.json
- libs/clusterd/project.json
- libs/clusterd/rollup.config.js
- libs/clusterd/src/index.ts
- libs/clusterd/tsconfig.json
- libs/clusterd/tsconfig.lib.json
- libs/clusterd/tsconfig.spec.json
- tsconfig.base.json
> Tests pass on final e2e PR: #726
- Extract clusterd control methods from `renterd-e2e` into a library for use across `renterd`, `hostd`, and `walletd` e2e test suites.
> refactor: extract clusterd library

- apps/hostd-e2e/playwright.config.ts
- apps/hostd-e2e/project.json
- apps/renterd-e2e/playwright.config.ts
- apps/renterd-e2e/project.json
- apps/walletd-e2e/playwright.config.ts
- apps/walletd-e2e/project.json
> Tests pass on final e2e PR: https://github.com/SiaFoundation/web/pull/726
- Install/override to the latest version of each daemon so that UI changes are always tested against the most recent commit.
- This will error out if the clusterd build fails, which lets us know clusterd needs to be updated.
- Configure playwright projects/browser with correct permissions.
- Configure playwright workers to the recommended 1 worker on CI (will be paralellized in later sharding PR)
- Up test timeouts to 120s as clusterd takes up to 30 seconds to initialize and form contracts.
> ci(e2e): cluster install latest daemons, configure playwright projects and workers

- .changeset/selfish-mice-relax.md
- .changeset/unlucky-lobsters-reply.md
- apps/explorer/components/Layout/Footer.tsx
- libs/design-system/src/components/ClientSideOnly.tsx
- libs/design-system/src/components/ThemeRadio.tsx
- libs/design-system/src/index.ts
This avoids the hydration error/warning we were receiving from the ThemeRadio component, concerning the clash between a client's localStorage theme preference and a server's lack of localStorage.
> fix(design-system): force the ThemeRadio component to render only on the client side

- .changeset/stale-actors-hunt.md
- apps/renterd-e2e/src/specs/config.spec.ts
- apps/renterd/contexts/config/fieldTips/Allowance.tsx
- apps/renterd/contexts/config/useAllowanceDerivedPricing.tsx
- Fixed an issue where the fit allowance suggestions were showing as NaN because all required fields were not filled.
> fix: renterd nan fit allowance values

- .changeset/early-bobcats-fry.md
- .changeset/eighty-eagles-taste.md
- .changeset/fair-carrots-reflect.md
- .changeset/late-onions-hammer.md
- .changeset/tiny-mails-guess.md
- apps/renterd-e2e/src/specs/hosts.spec.ts
- apps/renterd/contexts/config/useOnValid.tsx
- apps/renterd/contexts/hosts/columns.tsx
- apps/renterd/contexts/hosts/dataset.ts
- apps/renterd/contexts/hosts/index.tsx
- apps/renterd/contexts/hosts/status.ts
- apps/renterd/contexts/hosts/types.tsx
- libs/clusterd/src/index.ts
- libs/renterd-js/README.md
- libs/renterd-js/src/autopilot.ts
- libs/renterd-js/src/bus.ts
- libs/renterd-js/src/example.ts
- libs/renterd-react/src/autopilot.ts
- libs/renterd-react/src/bus.ts
- libs/renterd-react/src/worker.ts
- libs/renterd-types/src/autopilot.ts
- libs/renterd-types/src/bus.ts
- libs/renterd-types/src/types.ts
> All checks pass on final api-breakers PR: https://github.com/SiaFoundation/web/pull/743
- Removed deprecated search hosts and autopilot hosts APIs
- Added the new combined hosts API.
- The hosts explorer now uses the new combined hosts API.
- Added the bus list autopilots API.
- Fixed a bug optimistically updating last scan information when initiating a host scan.
> refactor(renterd): migrate hosts APIs

- .changeset/beige-cycles-change.md
- .changeset/cold-poems-appear.md
- .changeset/fifty-dots-do.md
- .changeset/poor-berries-sin.md
- .changeset/silent-icons-rule.md
- apps/hostd/contexts/transactions/index.tsx
- apps/renterd-e2e/src/specs/wallet.spec.ts
- apps/renterd/components/RenterdAuthedLayout.tsx
- apps/renterd/components/Wallet/StateError.tsx
- apps/renterd/components/Wallet/StateNoneMatching.tsx
- apps/renterd/components/Wallet/StateNoneYet.tsx
- apps/renterd/components/Wallet/WalletFilterBar.tsx
- apps/renterd/components/Wallet/index.tsx
- apps/renterd/contexts/transactions/columns.tsx
- apps/renterd/contexts/transactions/index.tsx
- apps/renterd/contexts/transactions/types.ts
- libs/design-system/src/app/AppAuthedLayout/Sidenav.tsx
- libs/design-system/src/app/AppAuthedLayout/SidenavItemWallet.tsx
- libs/design-system/src/app/AppAuthedLayout/index.tsx
- libs/design-system/src/app/WalletBalance.tsx
- libs/design-system/src/app/WalletBalanceSideNav.tsx
- libs/design-system/src/app/WalletBalanceTip.tsx
- libs/design-system/src/app/WalletLayoutActions.tsx
- libs/renterd-js/src/bus.ts
- libs/renterd-react/src/bus.ts
- libs/renterd-types/src/bus.ts
> All checks pass on final api-breakers PR: https://github.com/SiaFoundation/web/pull/743
This PR corresponds to the changes in: https://github.com/SiaFoundation/renterd/pull/1478
- Removed deprecated wallet transactions and pending transactions APIs.
- Added wallet events and pending events APIs.
- Removed deprecated wallet discard, fund, sign, and outputs APIs.
- The renterd transactions list is now includes more details such as specific transaction types and maturity height for locked siacoin.
> refactor(renterd): migrate to events APIs and remove other deprecated APIs

- .changeset/neat-foxes-carry.md
- .changeset/spotty-sheep-raise.md
- libs/renterd-types/src/bus.ts
- libs/renterd-types/src/types.ts
- package-lock.json
Relates to https://github.com/SiaFoundation/renterd/pull/1517
- The list objects API now includes a slabEncryptionKey parameter.
- The list objects API bucket parameter is now optional, and bucket is returned in in the object metadata.
> feat(renterd): list objects allows fetching across buckets

- apps/hostd-e2e/src/fixtures/volumes.ts
- apps/hostd-e2e/src/specs/volumes.spec.ts
- apps/hostd/components/Volumes/VolumeContextMenu.tsx
- apps/hostd/components/Volumes/index.tsx
- apps/hostd/dialogs/VolumeResizeDialog.tsx
> Small PR to add a missing test, no change in functionality.
- Add a test for resizing a volume.
- Adjust validation to use BigNumber operations.
> refactor(hostd): adjust resize volume validation, add test

- .changeset/cool-avocados-teach.md
- .changeset/popular-rocks-tie.md
- apps/renterd-e2e/src/fixtures/click.ts
- apps/renterd-e2e/src/fixtures/preferences.ts
- apps/renterd-e2e/src/fixtures/siascan.ts
- apps/renterd-e2e/src/specs/config.spec.ts
- apps/renterd-e2e/src/specs/configTips.spec.ts
- apps/renterd-e2e/src/specs/externalData.spec.ts
- apps/renterd-e2e/src/specs/files.spec.ts
- apps/renterd/contexts/config/fieldTips/MaxContractPrice.tsx
- apps/renterd/contexts/config/fieldTips/MaxDownloadPrice.tsx
- apps/renterd/contexts/config/fieldTips/MaxStoragePrice.tsx
- apps/renterd/contexts/config/fieldTips/MaxUploadPrice.tsx
- apps/renterd/contexts/config/fields.tsx
- apps/renterd/contexts/config/useAutopilotEvaluations.tsx
- apps/renterd/contexts/config/useAverages.tsx
- apps/renterd/contexts/config/useForm.tsx
- libs/design-system/src/app/CurrencyFiatSelector.tsx
- libs/sia-central-mock/src/siaCentralHostsNetworkAverages.ts
- Fixed a bug where the network average prices would show as 0 in the configuration fields.
- Max RPC price and max contract price now show a suggestion instead of a network average (10/million SC and 1 SC).
- The network averages were showing as near 0 values, which could direct the user to set them too low.
- Added handful of tests related to averages and fiat conversion.
> fix(renterd): network average prices

- .changeset/four-carpets-run.md
- .changeset/quick-bears-watch.md
- .changeset/twenty-ants-behave.md
- apps/renterd/contexts/hosts/columns.tsx
- libs/react-core/.eslintrc.json
- libs/react-core/README.md
- libs/react-core/jest.config.ts
- libs/react-core/jest.polyfills.js
- libs/react-core/package.json
- libs/react-core/src/index.spec.tsx
- libs/react-core/src/mutate.ts
- libs/react-core/src/request.ts
- libs/react-core/src/useDelete.ts
- libs/react-core/src/useGet.ts
- libs/react-core/src/usePatch.ts
- libs/react-core/src/usePost.ts
- libs/react-core/src/usePut.ts
- libs/react-core/src/utils.ts
- libs/react-core/src/workflows.tsx
- libs/request/src/index.ts
- Hooks keys are now a two element array that includes the request method. This fixes an issue where hooks using the same route on different methods could conflict. The mutation matcher still uses the route string without any method information.
- Migrated all settings interaction to the more specific requestSettings.
- Removed the unused standalone option.
> refactor: react-core hooks key format

- .changeset/chilly-dingos-sneeze.md
- .changeset/great-points-hide.md
- .changeset/mean-candles-develop.md
- .changeset/sharp-apples-love.md
- .changeset/sixty-ways-leave.md
- .changeset/wild-forks-unite.md
- libs/design-system/src/components/Table/index.tsx
- libs/design-system/src/core/Checkbox.tsx
- libs/design-system/src/index.ts
- libs/design-system/src/multi/MultiSelectionMenu.tsx
- libs/design-system/src/multi/useMultiSelect.spec.tsx
- libs/design-system/src/multi/useMultiSelect.tsx
> Video of how this works in next PR description: https://github.com/SiaFoundation/web/pull/783
- Added useMultiSelect hook that tracks multiselect state. It supports selection, shift-selecting for ranges, deselection, and works across pagination.
- Added MultiSelectMenu. The component can be used along with useMultiSelect for batch menus.
- Table column sort icons are now chevrons to differentiate from context menus which often use carets.
- Table now supports custom column heading components.
- Checkbox now supports an indeterminate state.
- Checkbox light mode background color is now white.
> feat: multiselect support

- .changeset/smooth-buses-pump.md
- libs/data-sources/src/lib/github.ts
- The latest walletd and renterd releases no longer include prereleases.
> fix(website): renterd and walletd provide latest full release

- .changeset/forty-bananas-return.md
- apps/renterd/contexts/config/useForm.tsx
- Fixed an issue where the app was sending invalid autopilot evaluation requests before all the required data was entered by the user.
> fix(renterd): stop sending invalid evaluations before initial validation

- .changeset/purple-terms-relax.md
- apps/website/components/DownloadDesktopSelect.tsx
- apps/website/content/downloads.spec.ts
- apps/website/content/downloads.ts
- Fixed an issue where the desktop download widget would not autoselect the correct OS download.
> fix(website): desktop download autoselect

- apps/renterd/contexts/config/useAutopilotEvaluations.tsx
- Adds an additional missing check for this fix: https://github.com/SiaFoundation/web/pull/793
- Changeset already included in first PR.
> fix(renterd): add autopilot configured check to evaluations

- .changeset/popular-guests-carry.md
- .changeset/stupid-planets-hide.md
- apps/renterd-e2e/src/specs/keys.spec.ts
- apps/renterd/components/Keys/KeysBatchMenu/KeysBatchDelete.tsx
- apps/renterd/components/Keys/KeysBatchMenu/index.tsx
- apps/renterd/components/Keys/KeysStatsMenu/index.tsx
- apps/renterd/components/Keys/index.tsx
- apps/renterd/contexts/keys/columns.tsx
- apps/renterd/contexts/keys/index.tsx
- apps/renterd/contexts/keys/types.ts
- libs/design-system/src/components/Table/TableRow.tsx
- libs/design-system/src/components/Table/index.tsx
- libs/design-system/src/core/Tooltip.tsx
- libs/design-system/src/multi/MultiSelectionMenu.tsx
- libs/design-system/src/multi/useMultiSelect.tsx
- This PR refines the multiselect API with learnings from adding it to the more complex files use-case in the subsequent PR.
- Selection is now via clicking anywhere on a table row rather than a special checkbox control.
- Table row data now supports an isSelected prop.
- The keys table now has pagination controls.
> refactor: refine multiselect API

- .changeset/loud-doors-learn.md
- .changeset/thirty-nails-raise.md
- apps/walletd/components/Node/index.tsx
- libs/hostd-types/src/api.ts
- libs/walletd-mock/src/mocks/peers.ts
- libs/walletd-types/src/types.ts
- hostd: The syncer peers response now includes more information and matches walletd.
- walletd: The syncer peers response type updated to include address rather than addr.
> refactor: standardize syncer peers response data

- apps/explorer-e2e/playwright.config.ts
- apps/hostd-e2e/playwright.config.ts
- apps/hostd-e2e/project.json
- apps/renterd-e2e/playwright.config.ts
- apps/renterd-e2e/project.json
- apps/renterd-e2e/src/fixtures/config.ts
- apps/renterd-e2e/src/specs/configTips.spec.ts
- apps/walletd-e2e/project.json
- Restore build-cluster behaviour to install tip of main branch for each daemon so tests always run against latest commit.
- Merge this in once api-breakers has been merged in renterd.
> test(e2e): restore cluster install latest

- apps/renterd-e2e/src/fixtures/files.ts
- apps/renterd-e2e/src/specs/files.spec.ts
- apps/renterd/lib/rename.ts
- This PR adds e2e tests that should pass once the renterd renaming glitch reported here is fixed: https://github.com/SiaFoundation/renterd/issues/1599
> test(renterd): directory rename and delete behaviour

- .changeset/neat-pumpkins-sparkle.md
- apps/explorer/app/host/[id]/page.tsx
- apps/explorer/components/Host/HostHeader.tsx
- apps/explorer/components/Host/HostInfo.tsx
- apps/explorer/components/Host/HostPricing.tsx
- apps/explorer/components/Host/HostSettings.tsx
- apps/explorer/components/Host/index.tsx
The only snaffu here is that the benchmark aspect of host is not ready yet, so I simply commented it out for now. I'll spawn a task for it.
> feat(explorer): replace Sia Central with explored API for the host route (minus benchmarks)

- .changeset/neat-goats-talk.md
- apps/explorer/app/contract/[id]/opengraph-image.tsx
- apps/explorer/app/contract/[id]/page.tsx
- apps/explorer/components/Contract/ContractHeader.tsx
- apps/explorer/components/Contract/index.tsx
- apps/explorer/components/ContractView/index.tsx
- apps/explorer/lib/contracts.ts
- apps/explorer/lib/time.ts
* The exact timestamp for negotiation, expiration, proof deadline, and payout are a bit off from Sia Central, but I believe that's expected. We're doing this on the client side now with respective block heights. The difference is not significant but I don't know how exact these are expected to be. `blockHeightToHumanDate` in `lib/contracts` would be the relevant pipe they are all flowing through.
* Payout is also a little different, too. I've never seen more that a few cents, but wanted to call that out, too. As far as I know, that's a difference on the explored side.
* Do the resolved from/to buttons work as we would expect? I believe so but it's hard to find good test contracts that have both. I've only see one or the other. It shouldn't matter, but I like to visually/manually test as …
> feat(explorer): use explored for the contracts route

- .changeset/brown-rings-buy.md
- apps/renterd/components/Hosts/HostContextMenu.tsx
- apps/renterd/contexts/hosts/columns.tsx
- libs/react-core/README.md
- libs/renterd-js/src/bus.ts
- libs/renterd-js/src/worker.ts
- libs/renterd-react/src/bus.ts
- libs/renterd-react/src/worker.ts
- libs/renterd-types/src/bus.ts
- libs/renterd-types/src/worker.ts
- The host scanning API was moved from the worker to the bus.
> refactor(renterd): move host scan API

- .changeset/angry-dingos-stare.md
- apps/renterd-e2e/src/fixtures/configResetSettings.ts
- apps/renterd/contexts/config/fields.tsx
- apps/renterd/contexts/config/transform.spec.ts
- apps/renterd/contexts/config/transformDown.ts
- apps/renterd/contexts/config/transformUp.ts
- apps/renterd/contexts/config/types.ts
- apps/renterd/contexts/config/useAutopilotEvaluations.tsx
- libs/renterd-types/src/types.ts
- Removed the allow redundant IPs setting.
> refactor(renterd): remove allow redundant IPs setting

- .changeset/selfish-queens-fold.md
- .changeset/ten-lies-draw.md
- .changeset/violet-peas-press.md
- apps/hostd-e2e/project.json
- apps/renterd-e2e/project.json
- apps/renterd/contexts/hosts/dataset.ts
- apps/renterd/contexts/hosts/index.tsx
- apps/walletd-e2e/project.json
- libs/clusterd/src/index.ts
- libs/renterd-js/README.md
- libs/renterd-js/src/autopilot.ts
- libs/renterd-js/src/bus.ts
- libs/renterd-js/src/example.ts
- libs/renterd-react/src/autopilot.ts
- libs/renterd-react/src/bus.ts
- libs/renterd-types/src/autopilot.ts
- libs/renterd-types/src/bus.ts
- libs/renterd-types/src/types.ts
- Autopilot config routes moved to the bus.
- The host checks field is now just HostAutopilotChecks.
- Removed the autopilotID parameter from the hosts API.
> refactor(renterd-libs): move autopilot routes

- .changeset/dirty-pianos-laugh.md
- .changeset/five-fireants-nail.md
- .changeset/forty-months-sin.md
- .changeset/honest-rats-cough.md
- .changeset/selfish-lemons-divide.md
- .changeset/shy-chicken-judge.md
- .changeset/sweet-chicken-suffer.md
- apps/renterd/components/Config/ConfigNav.tsx
- apps/renterd/components/ConfigEnabledSwitch.tsx
- apps/renterd/components/DockedControls.tsx
- apps/renterd/components/EnabledBar.tsx
- apps/renterd/components/Files/FilesStatsMenuShared/FilesStatsMenuWarnings.tsx
- apps/renterd/components/Files/checks/useAutopilotNotConfigured.tsx
- apps/renterd/components/Files/useCanUpload.tsx
- apps/renterd/components/FilesDirectory/EmptyState/index.tsx
- apps/renterd/components/OnboardingBar.tsx
- apps/renterd/contexts/config/index.tsx
- apps/renterd/contexts/config/transform.spec.ts
- apps/renterd/contexts/config/transformDown.ts
- apps/renterd/contexts/config/transformUp.ts
- apps/renterd/contexts/config/useAutopilotEvaluations.tsx
- apps/renterd/contexts/config/useOnValid.tsx
- apps/renterd/contexts/config/useResources.tsx
- apps/renterd/contexts/hosts/columns.tsx
- apps/renterd/contexts/hosts/index.tsx
- apps/renterd/contexts/hosts/types.tsx
- libs/renterd-types/src/autopilot.ts
- The configured boolean was removed from AutopilotState.
- Uploading files is no longer disabled if the user has not configured their settings.
- The configuration page navbar now has a switch for enabling or disabling autopilot.
- The file explorer warnings now include a warning for when autopilot is disabled, the warning relating to configuration status was removed.
- The onboarding bar no longer shows depending on the status of configuration but the first step still suggests configuring settings and enabling autopilot.
- If the autopilot is disabling a warning will appear on the bottom dock. The widget includes a switch for re-enabling the autopilot.
- The configuration no longer fills Sia Central network averages for max prices during first time configuration.
> refactor(renterd): autopilot move from configured to enabled

- .changeset/eighty-papayas-notice.md
- .changeset/light-pens-turn.md
- apps/renterd/components/Contracts/ContractContextMenu.tsx
- apps/renterd/components/Contracts/index.tsx
- apps/renterd/contexts/contracts/columns.tsx
- apps/renterd/contexts/contracts/dataset.tsx
- apps/renterd/contexts/contracts/index.tsx
- apps/renterd/contexts/contracts/types.ts
- apps/renterd/contexts/hosts/dataset.ts
- The contracts table now supports multi-select.
- The contract graphs are now explicitly toggled open with the action button in the navbar.
- This is a bit less jarring and also necessary since now selecting a row is primarily for taking action or multi-select, rather than specifically viewing the contract detail graphs.
- Screenshot of this in action in child PR: https://github.com/SiaFoundation/web/pull/828
> feat(renterd): contract multiselect

- .changeset/shy-dingos-roll.md
- apps/renterd-e2e/src/fixtures/hosts.ts
- apps/renterd-e2e/src/specs/contracts.spec.ts
- apps/renterd/components/Contracts/ContractsBatchMenu/ContractsAddAllowlist.tsx
- apps/renterd/components/Contracts/ContractsBatchMenu/ContractsAddBlocklist.tsx
- apps/renterd/components/Contracts/ContractsBatchMenu/ContractsRemoveAllowlist.tsx
- apps/renterd/components/Contracts/ContractsBatchMenu/ContractsRemoveBlocklist.tsx
- apps/renterd/components/Contracts/ContractsBatchMenu/index.tsx
- apps/renterd/components/Hosts/HostsAllowBlockDialog/AllowlistForm.tsx
- apps/renterd/components/Hosts/HostsAllowBlockDialog/BlocklistForm.tsx
- apps/renterd/components/Hosts/HostsAllowBlockDialog/index.tsx
- apps/renterd/hooks/useAllowlistUpdate.tsx
- apps/renterd/hooks/useBlocklistUpdate.tsx
- libs/design-system/src/core/PoolSelected.tsx
- The contracts multi-select menu now supports bulk adding and removing to both the allowlist and blocklists.
> feat(renterd): contracts bulk manage blocklist and allowlist

- .changeset/metal-numbers-impress.md
- .changeset/pink-buses-hear.md
- .changeset/sour-eagles-tickle.md
- apps/renterd-e2e/src/fixtures/contracts.ts
- apps/renterd-e2e/src/fixtures/hosts.ts
- apps/renterd-e2e/src/specs/contracts.spec.ts
- apps/renterd-e2e/src/specs/hosts.spec.ts
- apps/renterd/components/Hosts/HostContextMenu.tsx
- apps/renterd/components/Hosts/HostMap/Globe.tsx
- apps/renterd/components/Hosts/HostMap/index.tsx
- apps/renterd/components/Hosts/HostsBatchMenu/HostsAddAllowlist.tsx
- apps/renterd/components/Hosts/HostsBatchMenu/HostsAddBlocklist.tsx
- apps/renterd/components/Hosts/HostsBatchMenu/HostsRemoveAllowlist.tsx
- apps/renterd/components/Hosts/HostsBatchMenu/HostsRemoveBlocklist.tsx
- apps/renterd/components/Hosts/HostsBatchMenu/HostsResetLostSectorCount.tsx
- apps/renterd/components/Hosts/HostsBatchMenu/index.tsx
- apps/renterd/components/Hosts/Layout.tsx
- apps/renterd/components/Hosts/index.tsx
- apps/renterd/components/bulkActions/BulkAddAllowlist.tsx
- apps/renterd/components/bulkActions/BulkAddBlocklist.tsx
- apps/renterd/components/bulkActions/BulkRemoveAllowlist.tsx
- apps/renterd/components/bulkActions/BulkRemoveBlocklist.tsx
- apps/renterd/contexts/hosts/columns.tsx
- apps/renterd/contexts/hosts/dataset.ts
- apps/renterd/contexts/hosts/index.tsx
- apps/renterd/contexts/hosts/types.tsx
- libs/design-system/src/multi/useMultiSelect.tsx
- libs/renterd-types/src/bus.ts
- The hosts multi-select menu now supports bulk adding and removing to both the allowlist and blocklists.
- The hosts table now supports multi-select.
- The host map must now be explicitly toggled open with the action button in the navbar.
- This PR makes the bulk action components introduced in parent PR into generic components that can be used in both the host and contract contexts.
> feat(renterd): hosts multi-select and batch manage blocklist and allowlist

- .changeset/tasty-bobcats-admire.md
- apps/renterd-e2e/src/fixtures/configResetSettings.ts
- apps/renterd/components/Config/index.tsx
- apps/renterd/contexts/config/fields.tsx
- apps/renterd/contexts/config/transform.spec.ts
- apps/renterd/contexts/config/transformDown.ts
- apps/renterd/contexts/config/transformUp.ts
- apps/renterd/contexts/config/types.ts
- apps/renterd/contexts/config/useAutopilotEvaluations.tsx
- libs/renterd-types/src/types.ts
- The gouging settings no longer include migrationSurchargeMultiplier.
- Pending https://github.com/SiaFoundation/renterd/pull/1696
> refactor(renterd): remove hostBlockHeightLeeway and migrationSurchargeMultiplier

- .changeset/funny-jobs-sit.md
- .changeset/rotten-keys-smile.md
- .changeset/short-spoons-march.md
- .changeset/sweet-deers-end.md
- apps/renterd-e2e/src/fixtures/navigate.ts
- apps/renterd-e2e/src/specs/alerts.spec.ts
- apps/renterd/components/Files/Columns/FilesHealthColumn/FilesHealthColumnContents.tsx
- apps/renterd/components/Files/Columns/FilesHealthColumn/index.tsx
- apps/renterd/components/Files/FilesStatsMenuShared/FilesStatsMenuHealth.tsx
- apps/renterd/contexts/alerts/ChurnEventsField.tsx
- apps/renterd/contexts/alerts/columns.tsx
- apps/renterd/contexts/alerts/data.tsx
- apps/renterd/lib/fileHealth.tsx
- libs/renterd-types/src/bus.ts
- The set change alert was replaced with a churn alert that features a similar breakdown of contract changes with details such as reason and size.
- The slab migration failure alert was updated to match the new data format.
- The slab migration failure alert was updated to include a file health indicator.
- The alerts data is now full typed.
> refactor(renterd): alerts set change event replaced with similar churn event

- .changeset/sour-ants-swim.md
- .changeset/tame-files-dress.md
- .changeset/wicked-cycles-dress.md
- apps/hostd-e2e/src/fixtures/beforeTest.ts
- apps/hostd-e2e/src/fixtures/contracts.ts
- apps/hostd-e2e/src/fixtures/navigate.ts
- apps/hostd-e2e/src/specs/contracts.spec.ts
- apps/hostd/components/Contracts/ContractContextMenu.tsx
- apps/hostd/components/Contracts/ContractsBulkMenu/ContractsBulkIntegrityCheck.tsx
- apps/hostd/components/Contracts/ContractsBulkMenu/index.tsx
- apps/hostd/components/Contracts/Layout.tsx
- apps/hostd/components/Contracts/index.tsx
- apps/hostd/contexts/contracts/columns.tsx
- apps/hostd/contexts/contracts/dataset.ts
- apps/hostd/contexts/contracts/index.tsx
- apps/renterd-e2e/src/fixtures/beforeTest.ts
- libs/clusterd/package.json
- libs/clusterd/src/index.ts
- The contracts table now support multi-select.
- The contracts table now supports bulk integrity checks.
- `@siafoundaton/cluster`: Added distinct `renterdWaitForContracts` and `hostdWaitForContracts` methods.
> feat(hostd): contracts multi-select and bulk integrity check

- .changeset/grumpy-badgers-share.md
- apps/renterd/contexts/contracts/columns.tsx
- apps/renterd/contexts/contracts/dataset.tsx
- apps/renterd/contexts/contracts/types.ts
- apps/renterd/contexts/contracts/useFilteredStats.tsx
- libs/react-core/README.md
- libs/renterd-types/src/bus.ts
- libs/renterd-types/src/types.ts
- The contract total cost value is now called initial renter funds.
> refactor(renterd): contract total cost initial renter funds

- .changeset/green-baboons-sip.md
- .changeset/spotty-chefs-hang.md
- apps/hostd/components/Home/HomeBandwidth.tsx
- apps/hostd/components/Home/HomeOperations.tsx
- apps/hostd/components/Home/HomeStorage.tsx
- libs/design-system/src/core/ScrollArea.tsx
- Fixed an issue where the metrics graphs were much wider than the screen. https://github.com/SiaFoundation/hostd/issues/500
- Fixed a bug with ScrollArea where it would adopt its contents width.
> fix(hostd): home metrics graph width

- .changeset/rich-rats-try.md
- .changeset/spicy-dots-wait.md
- apps/renterd/contexts/config/transform.spec.ts
- apps/renterd/contexts/config/transformDown.ts
- apps/renterd/contexts/config/transformUp.ts
- libs/units/src/time.ts
- The min account expiry and min price table validity configuration settings are now stored in milliseconds.
> refactor(renterd): min account expiry and min price table validity units

- .changeset/late-points-learn.md
- apps/renterd-e2e/src/specs/files.spec.ts
- apps/renterd/contexts/config/transform.spec.ts
- apps/renterd/contexts/filesManager/downloads.tsx
- Fixed an issue where the first attempt to download a file would show a bucket not found error.
- Strange issue where buckets.data is still undefined in the closure even though the data has been fetched. Adding useCallback does the trick, oddly even just console logging buckets.data above downloadFiles fixes the issue.
> fix(renterd): first file download no bucket error

- .changeset/slow-roses-hide.md
- apps/explorer-e2e/src/specs/block.spec.ts
- apps/explorer/app/block/[id]/page.tsx
- apps/explorer/components/Block/index.tsx
I played with the positioning of these two buttons (next to block height, center, etc) and whether to write out "previous block" and "next block" or not. I settled with this and a tooltip. Included catching the < 1 and > current block height cases.
> feat(explorer): add previous and next block navigation to block page

- .changeset/sharp-ears-tell.md
- apps/hostd-e2e/src/fixtures/configResetAllSettings.ts
- apps/hostd-e2e/src/specs/config.spec.ts
- apps/hostd/contexts/config/fields.tsx
- Address configuration setting now expects only the hostname without a port. https://github.com/SiaFoundation/hostd/issues/536
> fix(hostd): address configuration hostname no port

- .changeset/polite-doors-do.md
- apps/renterd-e2e/src/specs/files.spec.ts
- apps/renterd/contexts/filesDirectory/columns.tsx
- apps/renterd/contexts/filesDirectory/index.tsx
- Fixed an issue where selecting the entire page of files would select the parent navigation row.
> fix(renterd): files directory mode page select ignores parent dir

- .changeset/silver-pants-deliver.md
- .changeset/thick-geckos-laugh.md
- apps/renterd/components/Files/Columns/FilesHealthColumn/FilesHealthColumnContents.tsx
- apps/renterd/components/Files/FileContextMenu/CopyMetadataMenuItem.tsx
- libs/renterd-types/src/bus.ts
- Fixed an issue with the copy file metadata action in the file context menu.
- The object response has been updated in v2.
> fix(renterd): files copy metadata

- .changeset/stupid-clocks-fail.md
- apps/hostd-e2e/src/fixtures/contracts.ts
- apps/hostd-e2e/src/fixtures/volumes.ts
- apps/hostd-e2e/src/specs/contracts.spec.ts
- apps/hostd-e2e/src/specs/volumes.spec.ts
- apps/hostd/components/Volumes/index.tsx
- apps/hostd/contexts/volumes/index.tsx
- apps/renterd-e2e/src/fixtures/files.ts
- apps/renterd-e2e/src/fixtures/uploads.ts
- apps/renterd-e2e/src/specs/contracts.spec.ts
- apps/renterd-e2e/src/specs/files.spec.ts
- apps/renterd-e2e/src/specs/filesMove.spec.ts
- apps/renterd-e2e/src/specs/hosts.spec.ts
- apps/renterd-e2e/src/specs/pagination.spec.ts
- apps/renterd/components/Uploads/UploadsTable.tsx
- apps/renterd/contexts/uploads/index.tsx
- libs/design-system/src/components/PaginatorKnownTotal.tsx
- libs/design-system/src/components/PaginatorMarker.tsx
- libs/design-system/src/components/PaginatorUnknownTotal.tsx
- libs/design-system/src/hooks/useSorting.ts
- libs/design-system/src/hooks/useTableState.ts
- Tests for renterd files and uploads pagination.
- Test for hostd contracts and volumes pagination.
- e2e: Added support for uploading files of a specific size.
> test(renterd): files and uploads pagination and other tests

- .changeset/gorgeous-coins-begin.md
- apps/renterd/contexts/filesManager/downloads.tsx
- The copyable file download URLs in the file context menu have been updated to match the new API.
- The URL was still objects/:key instead of object/:key
> fix(renterd): object download urls

- .changeset/funny-icons-grab.md
- .changeset/silly-vans-film.md
- apps/hostd/components/Profile/index.tsx
- libs/units/src/entityTypes.ts
- The host net address context menu no longer has a view on siascan option. https://github.com/SiaFoundation/hostd/issues/554
- The host wallet address context menu now has a view on siascan option.
> fix(hostd): net address and wallet address view on siascan changes

- .changeset/strange-pigs-begin.md
- apps/renterd-e2e/src/specs/alerts.spec.ts
- apps/renterd/contexts/alerts/ChurnEventsField.tsx
- apps/renterd/contexts/contracts/index.tsx
- Fixed an issue with the contract churn alert's overall churn percentage.
- The percentage is now the size of contracts in the churn alert that have moved to a 'bad' state over the total size of all contracts. Previously it was assumed the churn alert always included all contracts.
> fix(renterd): contract churn alert percentage

- .changeset/light-ladybugs-speak.md
- .changeset/mighty-news-float.md
- apps/renterd-e2e/src/specs/alerts.spec.ts
- apps/renterd/contexts/alerts/columns.tsx
- libs/design-system/src/core/ExpandableText.tsx
- libs/design-system/src/index.ts
- Alerts with large errors are now collapsed by default and have a control to expand and collapse the full contents.
<div class='graphite__hidden'>
<div>🎥 Video uploaded on Graphite:</div>
<a href="https://app.graphite.dev/media/video/cleTojt8wre2nDvCJHng/3ceec7a5-bbb6-4cc6-a664-43b9c3777c47.mp4">
</a>
</div>
<video src="https://graphite-user-uploaded-assets-prod.s3.amazonaws.com/cleTojt8wre2nDvCJHng/3ceec7a5-bbb6-4cc6-a664-43b9c3777c47.mp4">showmore.mp4</video>
> feat(renterd): alerts collapse large errors

- .changeset/good-shirts-behave.md
- apps/explorer-e2e/src/fixtures/constants.ts
- apps/explorer/app/address/[id]/opengraph-image.tsx
- apps/explorer/app/address/[id]/page.tsx
- apps/explorer/components/Address/index.tsx
- apps/explorer/components/AddressSkeleton/index.tsx
Replacing the API here forced a decision around event display, so this has some small UI changes:
* References to transactions in the upper right corner and the tab are now "events". Changed the skeleton to match.
* Items in the event list are now labeled more granularly with the type of event and hopefully all the relevant linking. (Need a check on this for sure)
> feat(explorer): use explored for the address route

- .changeset/fluffy-pumas-float.md
- .changeset/four-apes-work.md
- apps/renterd-e2e/src/specs/files.spec.ts
- apps/renterd/components/Files/FileContextMenu/index.tsx
- apps/renterd/components/TransfersBar.tsx
- apps/renterd/contexts/filesManager/downloads.tsx
- apps/renterd/contexts/filesManager/index.tsx
- Files are now downloaded directly in the browser with cookie based auth. (instead of first into memory)
- The transfers bar no longer includes a download list.
- Subject to change based on https://github.com/SiaFoundation/renterd/pull/1806
> refactor(renterd): native direct file downloads

- .changeset/chilled-days-live.md
- .changeset/itchy-paws-call.md
- .changeset/light-ravens-own.md
- apps/renterd/contexts/filesManager/types.ts
- apps/renterd/contexts/filesManager/uploads.tsx
- apps/renterd/contexts/filesManager/useWarnActiveUploadsOnClose.tsx
- apps/renterd/contexts/uploads/index.tsx
- apps/renterd/lib/multipartUpload.ts
- libs/react-core/package.json
- libs/react-core/src/index.ts
- libs/react-core/src/throttle.test.ts
- libs/react-core/src/throttle.ts
- libs/react-core/src/useThrottledStateMap.ts
- libs/renterd-react/package.json
- libs/renterd-react/src/bus.ts
- package-lock.json
- package.json
- The application no longer lags when uploading thousands of files.
- The performance was improved with the following two changes:
- The uploads state map which can store thousands of records and receive hundreds of progress updates per second was moved to ref-based mutable state.
- Multipart uploads are now created when they are popped off the queue and start uploading, previously adding a directory with thousands of files would immediately create a multpart upload session for every file.
> refactor(renterd): improve uploads performance

- .changeset/quiet-maps-attend.md
- apps/explorer/components/Layout/Search.tsx
This PR replaces Sia Central with explored, for the explorer search feature.
Down stack, we add the 'host' SearchResultType return. Before the [connected](https://github.com/SiaFoundation/explored/pull/161) PR hits, if a user searches for a host pubkey with the `ed25519` prefix, we will succeed. If not prefixed, we will hit the error case (and tell the user the request failed) but, after the PR hits, this should just work.
> feat(explorer): use explored for search

- .changeset/chilled-humans-begin.md
- apps/renterd/components/Files/FilesStatsMenuShared/FilesStatsMenuCount.tsx
- The total number of files no longer includes uploads in progress.
> fix(renterd): remove uploads from total files count

- .changeset/heavy-ducks-work.md
- .changeset/slimy-coats-sneeze.md
- libs/react-core/src/appSettings/useExternalData/currency.ts
- libs/sia-central-mock/src/siaCentralExchangeRates.ts
- libs/sia-central-types/src/exchangeRates.ts
- Updated the list of currencies to those supported by explored.
- Removed unsupported currencies from Sia Central SDKs.
> fix: update supported fiat exchange currencies

- .changeset/healthy-moles-unite.md
- .changeset/tiny-donkeys-do.md
- apps/renterd-e2e/src/specs/files.spec.ts
- apps/renterd-e2e/src/specs/pagination.spec.ts
- apps/renterd/contexts/filesManager/dataset.tsx
- apps/renterd/contexts/filesManager/types.ts
- apps/renterd/contexts/filesManager/useFilesTableState.tsx
- Fixed an issue where files were being sorted by name rather than full path in all files mode.
- The sort field is called `name` so it was sorting on the `name` on the client - the server is really sorting on the full path when returning delimiter="" results.
- The reason we have to re-apply the sorting at all on the client-side because we naturally weave in any active uploads that fit into the current directory or the all files view. This is to achieve a UX where uploads show immediately just in a "syncing" state as seen in iCloud, Dropbox, etc.
- The default files sort direction is now asc instead of desc.
> fix(renterd): files name sort is on path

- apps/hostd-e2e/src/fixtures/volumes.ts
- apps/hostd-e2e/src/specs/volumes.spec.ts
- Volume removal now takes longer so tests can no rely on the presence of the volume row to verify removal since it can take longer than the test timeout for the row to disappear. Instead we now verify removal by only checking the status has changed to removing.
> fix(hostd): volume delete fixture

- .changeset/warm-toys-end.md
- apps/walletd/dialogs/WalletSendLedgerDialog/useSign.tsx
- apps/walletd/dialogs/WalletSendSeedDialog/useSignAndBroadcast.tsx
- libs/walletd-mock/src/mocks/walletOutputsSiacoin.ts
- libs/walletd-mock/src/mocks/walletOutputsSiafund.ts
- libs/walletd-types/src/api.ts
- Updated the response structure for outputs APIs.
> fix(walletd-libs): update wallet outputs response

- .changeset/forty-shoes-sit.md
- .changeset/quick-lobsters-repeat.md
- .changeset/swift-bears-decide.md
- libs/design-system/src/app/WalletAddressCode.tsx
- libs/design-system/src/components/ValueCopyable.tsx
- Displayed entity values which are often truncated can now be copied to clipboard by double-clicking directly on the visible characters.
- Wallet addresses can now be copied to clipboard by clicking on the QR code in the address dialog.
> feat: streamline copy value and address

- .changeset/slow-flowers-remain.md
- .changeset/stale-pillows-exist.md
- internal/cluster/cmd/clusterd/main.go
- libs/clusterd/src/index.ts
This PR adds cluster support for testing across the v2 fork activation heights.
- Added transition network mode.
- Added mineToHeight and getCurrentHeight APIs.
> feat(cluster): v2 transition support

- .changeset/cool-tomatoes-deliver.md
- .changeset/friendly-houses-matter.md
- .changeset/tidy-lobsters-float.md
- libs/sdk/src/rhp.spec.ts
- libs/sdk/src/types.ts
- libs/types/src/utils.ts
- sdk/wallet.go
> This PR adds methods to SDK required for sending v2 transactions in walletd.
- Added v2TransactionInputSigHash and signHash methods to API.
- Improved the accuracy of all return types.
> refactor(sdk): sdk cleanup

- .changeset/rich-suits-bake.md
- apps/explorer/app/host/[id]/opengraph-image.tsx
- apps/explorer/components/Home/HostListItem.tsx
- apps/explorer/components/Host/HostPricing.tsx
Slight visual changes on this one for the hosts list on the home page to fix some consequences of removing the two benchmark subvalues:
* Remaining storage moves to a "primary" value with its own icon
* Removed justify-between for these now four items - this felt too spaced out with the smaller amount of text. Runner up visually for me was justify-around, but I like unset better.
* ~~At the lower width breakpoint, now storage cost and download cost stay visible.~~ Downstack, we've introduced 2xs and 3xs container breakpoints to `theme` and used container queries to makes this more responsive.
> feat(explorer): remove host benchmarks

- .changeset/hungry-monkeys-wonder.md
- .changeset/perfect-turtles-kiss.md
- .changeset/tiny-deers-wink.md
- .changeset/tricky-carrots-deny.md
- apps/walletd/contexts/addresses/dataset.tsx
- apps/walletd/contexts/addresses/types.ts
- apps/walletd/dialogs/WalletSendLedgerDialog/useFundAndSign.tsx
- apps/walletd/dialogs/WalletSendLedgerDialog/useSendForm.tsx
- apps/walletd/dialogs/WalletSendSeedDialog/useSignAndBroadcast.tsx
- apps/walletd/dialogs/_sharedWalletSend/useBroadcast.tsx
- apps/walletd/dialogs/_sharedWalletSend/useFund.tsx
- apps/walletd/lib/signLedger.spec.ts
- apps/walletd/lib/signSeed.spec.ts
- libs/types/src/v2.ts
- libs/walletd-js/src/index.ts
- libs/walletd-mock/src/mocks/walletFundSiacoin.ts
- libs/walletd-mock/src/mocks/walletFundSiafund.ts
- libs/walletd-mock/src/scenarios/seedWallet.ts
- libs/walletd-react/src/api.ts
- libs/walletd-types/src/api.ts
- Added construct APIs for both v1 and v2 transactions.
- Added the basis ChainIndex parameter to txpool broadcast API.
- Added the basis ChainIndex value to txpool transactions response.
> feat(walletd-libs): construct api and v2 api changes

- libs/hostd-types/src/api.ts
- libs/hostd-types/src/types.ts
- libs/renterd-types/src/types.ts
- Unused transaction types. We have since moved to Events.
> refactor: remove unused types

- .changeset/healthy-pears-listen.md
- .changeset/poor-foxes-poke.md
- .changeset/wise-candles-swim.md
- apps/walletd/dialogs/WalletAddLedgerDialog/index.tsx
- apps/walletd/dialogs/WalletAddressesGenerateLedgerDialog/index.tsx
- apps/walletd/dialogs/WalletAddressesGenerateSeedDialog/index.tsx
- apps/walletd/dialogs/WalletSendSeedDialog/useSignAndBroadcast.tsx
- apps/walletd/lib/__snapshots__/signSeedV1.spec.ts.snap
- apps/walletd/lib/__snapshots__/signSeedV2.spec.ts.snap
- apps/walletd/lib/signLedger.spec.ts
- apps/walletd/lib/signLedger.ts
- apps/walletd/lib/signSeedV1.spec.ts
- apps/walletd/lib/signSeedV1.ts
- apps/walletd/lib/signSeedV2.spec.ts
- apps/walletd/lib/signSeedV2.ts
- apps/walletd/lib/signV1.ts
- apps/walletd/lib/signV2.ts
- libs/walletd-mock/src/mocks/walletAddresses.ts
- libs/walletd-mock/src/scenarios/seedWallet.ts
- libs/walletd-types/src/types.ts
- Generating addresses now stores the `spendPolicy` in the dedicated field rather than `unlockConditions` in the metadata.
- V1 signing now uses the address `spendPolicy`.
- Added V2 signing method.
> feat(walletd): v2 seed signing

- .changeset/odd-cycles-accept.md
- apps/walletd-e2e/src/specs/seedSendSiafund.spec.ts
- apps/walletd/dialogs/_sharedWalletSendV1/useComposeFormV1.tsx
- apps/walletd/dialogs/_sharedWalletSendV2/useComposeFormV2.tsx
- Send mode only sends the amount of siacoin or siafunds specified in the active mode.
> fix(walletd): switching send modes unsets other amount

- .changeset/slimy-bags-beam.md
- apps/walletd-e2e/src/specs/ledgerSendSiacoin.spec.ts
- apps/walletd-e2e/src/specs/ledgerSendSiafund.spec.ts
- apps/walletd/dialogs/WalletSendLedgerDialog/index.tsx
- apps/walletd/dialogs/WalletSendSeedDialog/index.tsx
- apps/walletd/dialogs/_sharedWalletSendV2/hardforkV2.ts
- Updated ledger wallets to continue sending v1 txn after the allow height and disable at the require height.
- Added tests that check the 3 phases.
- Seed wallets still switch to v2 at the allow height.
> refactor(walletd): ledger wallet warn at require height

- .changeset/wild-adults-tie.md
- apps/walletd-e2e/src/fixtures/ledgerComposeSiacoin.ts
- apps/walletd-e2e/src/fixtures/ledgerComposeSiafund.ts
- apps/walletd-e2e/src/fixtures/seedSendSiacoin.ts
- apps/walletd-e2e/src/fixtures/seedSendSiafund.ts
- apps/walletd-e2e/src/specs/ledgerSendSiacoin.spec.ts
- apps/walletd-e2e/src/specs/ledgerSendSiafund.spec.ts
- apps/walletd-e2e/src/specs/seedSendSiacoin.spec.ts
- apps/walletd-e2e/src/specs/seedSendSiafund.spec.ts
- apps/walletd/dialogs/WalletSendLedgerDialog/WalletSendLedgerDialogV1/index.tsx
- apps/walletd/dialogs/WalletSendLedgerDialog/WalletSendLedgerDialogV2/index.tsx
- apps/walletd/dialogs/WalletSendLedgerDialog/index.tsx
- apps/walletd/dialogs/WalletSendSeedDialog/WalletSendSeedDialogV1/index.tsx
- apps/walletd/dialogs/WalletSendSeedDialog/WalletSendSeedDialogV2/index.tsx
- apps/walletd/dialogs/WalletSendSeedDialog/index.tsx
- apps/walletd/dialogs/_sharedWalletSend/TransactionVersionIndicator.tsx
- apps/walletd/dialogs/_sharedWalletSend/hardforkV2.ts
- apps/walletd/dialogs/_sharedWalletSendV1/SendFlowDialogV1.tsx
- apps/walletd/dialogs/_sharedWalletSendV2/SendFlowDialogV2.tsx
- The send dialogs now indicate the network and transaction version details.
- Added for more visibility and easier future debugging.
> feat(walletd): send network and transaction version details

- .changeset/metal-rats-smile.md
- libs/react-core/src/useExchangeRate.tsx
This is temporary. We'll eventually need to coordinate changing this over to explored, and then we can remove the parameter drilling.
> feat(react-core): add optional API parameter to useExchangeRates methods

- .changeset/gentle-jobs-compare.md
- apps/explorer/components/Contract/index.tsx
- apps/explorer/components/LoadingTimestamp.tsx
- apps/explorer/components/Transaction/TransactionHeader.tsx
- libs/design-system/src/components/BlockList.tsx
This PR puts the result of `blockHeightToHumanDate` operations within the `explorer` totally on the client's side, using a ... `animate-pulse` fallback. As far as client is concerned, I expect them to barely experience this fallback given the speed of the operation (EDIT: looking at the live preview, this appears to be true. It's basically imperceptible.). We do also benefit visually here by not showing the server timestamp and then switching to the client's. However, the biggest gain is in local development under `strict mode`, as affected components were switching to client-side rendering. This should help us more accurately assess clients' loading experience in development, which I believe is a strong reason to take this approach.
> refactor(explorer): use client side rendering for timestamps

- .eslintignore
- Ensures the new next directories introduced in #958 are not linted.
> chore: eslint ignore .next-*

- .changeset/flat-beds-hope.md
- .changeset/slow-carpets-add.md
- apps/walletd/dialogs/WalletSendSeedDialog/WalletSendSeedDialogV2/useSignAndBroadcastV2.tsx
- apps/walletd/lib/__snapshots__/signSeedV2.spec.ts.snap
- apps/walletd/lib/signSeedV2.spec.ts
- apps/walletd/lib/signSeedV2.ts
- apps/walletd/lib/signV2.ts
- libs/clusterd/src/index.ts
- libs/types/src/v2.ts
When signing a V2 transaction if the wallet does not have any Siafund inputs, "No outputs" is returned. This simplifies the signing logic by using the metadata already on the input instead of fetching the list of inputs from the wallet first.
> fix(walletd,types): fix signing v2 transactions

- .changeset/brown-news-draw.md
- apps/explorer/app/host/[id]/opengraph-image.tsx
- apps/explorer/components/Home/HostListItem.tsx
- apps/explorer/components/Home/index.tsx
- apps/explorer/components/Host/HostHeader.tsx
- apps/explorer/components/Host/HostInfo.tsx
- apps/explorer/components/Host/HostPricing.tsx
- apps/explorer/components/Host/HostSettings.tsx
- apps/explorer/components/Host/index.tsx
- apps/explorer/lib/hostType.ts
- apps/explorer/lib/hosts.ts
- apps/explorer/tsconfig.json
- libs/explored-types/src/types.ts
This adds support for the v2 Host type in the explorer and closes #971.
There are two sharper edges here I see worth discussing, of the same ilk:
* Down stack, in the types update, we are going with a different typing strategy than `explored`--instead of being additive to `ExplorerHost`, we break this out into two types. One for v1 and one for v2, discriminating on `v2: boolean`.
* We also add a lot of `host.v2 ? ...` logic across the host slice of the explorer. I don't think this would be avoided by using one additive type. We'd instead be checking for `settings`, `priceTable`, and `rhpV4Settings` all the same. I've created some helpers around getting the netAddress and the settings as they pertain to checking whether they exist (is this a legacy assumption? It doesn't match the …
> feat(explorer): add v2 host type support

- .changeset/mighty-lamps-occur.md
- apps/explorer/components/Host/HostHeader.tsx
- apps/explorer/components/Host/index.tsx
- apps/explorer/lib/hostType.ts
We were carrying over a legacy Sia Central assumption here around the existence of  `host.settings`. With explored, we should instead rely on `host.successfulInteractions`.
> refactor(explorer): rely on successfulInteractions for unscanned hosts

- apps/explorer-e2e/project.json
- apps/explorer/tsconfig.json
- Add missing build dependencies. This will ensure all libraries used in explorer-e2e are automatically built before the e2e target runs.
> chore(explorer-e2e): e2e target should build dependencies

- .changeset/blue-pugs-perform.md
- apps/explorer/components/Home/index.tsx
The reason for this change is that hosts can set wildly high or low prices and throw off our averages. `explored` now supplies median, instead.
> feat(explorer): change average price titles to median

- .changeset/fifty-carrots-pay.md
- .changeset/grumpy-jars-tell.md
- libs/types/src/events.ts
- libs/units/src/events.ts
- Fixed an issue where a v2ContractResolution event in the wallet would crash the app. https://github.com/SiaFoundation/hostd/issues/629
- Removed parent from the data field of WalletEventContractResolutionV2.
> fix(hostd): issue with events v2ContractResolution type

- apps/hostd-e2e/src/specs/contracts.spec.ts
- Check the payout height on the actual timeline, this is more inline with the goal of the test and is more deterministic.
> test(hostd): contract timeline deterministic payout check

- .changeset/slow-cherries-remain.md
- apps/hostd/contexts/volumes/columns.tsx
- apps/hostd/contexts/volumes/types.ts
- The volumes list now has an ID column. https://github.com/SiaFoundation/hostd/issues/635
> feat(hostd): volume ID column

- .changeset/slow-cherries-remain.md
- .changeset/twenty-items-lay.md
- apps/hostd/components/Volumes/VolumesFiltersBar.tsx
- Fixed the alignment of volume stats in the subnav.
> fix(hostd): volume stats alignment

- .changeset/purple-keys-sniff.md
- apps/explorer/components/Home/HostListItem.tsx
- apps/explorer/components/Host/HostSettings.tsx
- apps/explorer/lib/hosts.ts
- Fixed the units for v2 host settings total and remaining storage.
- These fields were in bytes in v1, for v2 they are in sectors.
> fix(explorer): v2 total and remaining storage to bytes

- apps/walletd/lib/mocks/mockConsensusNetwork.ts
- apps/walletd/lib/mocks/mockConsensusTipState.ts
- apps/walletd/lib/mocks/mockSeedWallet.ts
- apps/walletd/lib/signLedgerV1.spec.ts
- apps/walletd/lib/signSeedV1.spec.ts
- apps/walletd/lib/signSeedV2.spec.ts
- Move a copy of these mocks right to where they are used. The entire walletd-mock library is being deleted in subsequent PR.
> refactor(walletd): move test mocks into walletd

- .changeset/unlucky-turkeys-clean.md
- apps/hostd-e2e/src/specs/contracts.spec.ts
- apps/hostd/contexts/contracts/dataset.ts
- libs/hostd-types/src/types.ts
- V2Contract resolutionHeight is now resolutionIndex. Relates to https://github.com/SiaFoundation/hostd/pull/634
> refactor(hostd): V2Contract resolutionIndex name

- .changeset/four-crews-cough.md
- .changeset/real-foxes-fetch.md
- apps/explorer/components/HardforkCountdown/index.tsx
- apps/explorer/components/Layout/index.tsx
- apps/explorer/components/SyncWarning/index.tsx
- apps/explorer/lib/sync.ts
- Made some tweaks around sync status since the node height is not the actual network height until fully synced.
- The hardfork countdown only shows if the explorer is fully synced.
- The explorer now shows a warning banner if syncing is in progress.
> feat(explorer): sync banner, hardfork banner sync

- apps/explorer/app/contract/[id]/opengraph-image.tsx
- apps/explorer/components/Contract/index.tsx
- apps/explorer/components/Host/HostSettings.tsx
- apps/explorer/lib/currency.ts
- Small change to make method name more specific/accurate.
> refactor(explorer): hastings to fiat method name

- .changeset/lemon-ghosts-sin.md
- .changeset/lovely-crews-build.md
- .changeset/olive-crabs-sparkle.md
- apps/renterd/components/Hosts/HostsViewDropdownMenu.tsx
- apps/renterd/contexts/hosts/columns.tsx
- apps/renterd/contexts/hosts/dataset.ts
- apps/renterd/contexts/hosts/types.tsx
- The host explorer now has a version column.
- The host explorer now has columns for v2 settings.
> feat(renterd): host explorer v2 settings columns

- .changeset/clean-ducks-carry.md
- .changeset/wet-colts-care.md
- apps/hostd-e2e/src/fixtures/contracts.ts
- apps/hostd-e2e/src/specs/contracts.spec.ts
- apps/hostd/components/Contracts/ContractsCmd/ContractsFilterCmd/ContractFilterCmdGroups/Status.tsx
- apps/hostd/components/Contracts/ContractsFiltersBar.tsx
- apps/hostd/contexts/contracts/dataset.ts
- apps/hostd/contexts/contracts/index.tsx
- apps/hostd/contexts/contracts/types.ts
- apps/hostd/dialogs/ContractsFilterContractIdDialog.tsx
- Extends the work (and reverts the change from server to client filtering) done in https://github.com/SiaFoundation/web/pull/989 and adds two distinct modes.
- The contract explorer now has distinct v1 and v2 viewing modes.
- Fixed an issue where the contract explorer did not show the correct total number of contracts.
> fix(hostd): contact explorer total and modes

- apps/explorer-e2e/src/fixtures/constants.ts
- apps/explorer-e2e/src/specs/contract.spec.ts
This disables the tests that will fail as a result of disabling the renewedFrom and renewedTo buttons until such time as those are available. That said, the next PR up the stack will fail. The one after that I'm aiming to succeed with this PR. The final one, adjusting the testing suite to fully utilize clusterd, obviously changes all this. I wanted to see the pre-cluster testing succeed to verify assumptions, if that makes sense.
> test(explorer): disable contract renewedFrom, renewedTo, and adjust constant

- .changeset/wild-pianos-hammer.md
- apps/explorer-e2e/project.json
- apps/hostd-e2e/src/fixtures/volumes.ts
- internal/cluster/cmd/clusterd/main.go
- internal/cluster/go.mod
- internal/cluster/go.sum
- libs/clusterd/src/index.ts
- libs/design-system/README.md
PR with a bunch of improvements found while debugging the cluster startup issues:
- Update cluster deps.
- Improve flaky hostd volume test.
- Removed unnecessary `^build` from the explorer-e2e e2e target (should make startup _much_ faster, it was doing a production (slow) build of explorer that was not even being used cc @telestrial)
- Fixed `waitFor`. If the condition hung or errored would prevent natural test timeout on CI.
- Fixed -explored=1 startup errors in `cmd`.
> fix(e2e): stabilize e2e tests

- .changeset/honest-poems-shake.md
- apps/explorer/components/Entity/EntityListItem.tsx
Pretty straightforward: on the block and transaction pages, transactions and contract entities had avatars and IDs that were clickable, but the title wasn't. That felt counter-intuitive.
> feat(explorer): add link to entity list titles, when appropriate

- .changeset/large-gorillas-protect.md
- apps/walletd/dialogs/WalletSendLedgerDialog/index.tsx
- apps/walletd/dialogs/WalletSendSeedDialog/index.tsx
- apps/walletd/dialogs/_sharedWalletSend/TransactionVersionIndicator.tsx
- apps/walletd/dialogs/_sharedWalletSend/hardforkV2.ts
- internal/cluster/cmd/clusterd/main.go
- The wallet send features now use hardfork heights from the consensus network data instead of hardcoded heights. Closes https://github.com/SiaFoundation/web/issues/990
> fix(walletd): dynamic hardfork heights

- .changeset/green-spiders-behave.md
- apps/explorer/app/address/[id]/opengraph-image.tsx
- apps/explorer/app/address/[id]/page.tsx
- apps/explorer/app/block/[id]/opengraph-image.tsx
- apps/explorer/app/block/[id]/page.tsx
- apps/explorer/app/contract/[id]/opengraph-image.tsx
- apps/explorer/app/contract/[id]/page.tsx
- apps/explorer/app/host/[id]/opengraph-image.tsx
- apps/explorer/app/host/[id]/page.tsx
- apps/explorer/app/tx/[id]/opengraph-image.tsx
- apps/explorer/app/tx/[id]/page.tsx
- apps/explorer/components/Transaction/index.tsx
- apps/explorer/lib/hosts.ts
- apps/explorer/lib/identicon.d.ts
- apps/explorer/lib/pageProps.ts
- apps/explorer/lib/utils.ts
- apps/explorer/tsconfig.json
This refactor for typescript strict mode was fairly straightforward. Biggest change by number of files touched was simply typing out `params: { id: string }`. I unified that prop type and made it extensible, just in case it ever needs to be. Beyond that:
* The rankHosts function needed a decent rewrite, and I suspect that, previous to this, it was at least somewhat broken. I believe we were referencing keys that didn't exist, and I'm guessing that was skewing the final result. Should I throw a changeset on that, since the resultant list is now an entirely different group of hosts?
* Satisfying strict mode for the Transaction slice was fairly verbose. Lots of novel `'key' in object ? ... : ...`. It does probably need consolidating earlier. There is some decision-making to do there about …
> refactor(explorer): typescript strict mode

- .changeset/late-needles-wonder.md
- apps/walletd/lib/mocks/mockSeedWallet.ts
- libs/walletd-types/src/api.ts
- libs/walletd-types/src/types.ts
- Elements returned by unspent outputs endpoints now include the number of confirmations.
> feat(walletd-libs): unspent outputs now include confirmations

- .changeset/kind-flowers-scream.md
- apps/explorer/components/Host/HostInfo.tsx
> fix(explorer): round host uptime percentage to hundredths place

- .changeset/brave-boats-burn.md
- apps/explorer/middleware.ts
This PR adds middleware to the Explorer that enforces lowercased IDs across the `address`, `block`, `contract`, `host`, and `tx` routes.
For example, if a user navigates to `https://zen.siascan.com/address/E254b0e6500cbe7eba250e0f60f90fb46eade419554b7a5eda6e83ef38554dda0486af517d0b` or enters that same uppercase "E" ID in the search bar, they will be redirected to `https://zen.siascan.com/address/e254b0e6500cbe7eba250e0f60f90fb46eade419554b7a5eda6e83ef38554dda0486af517d0b`.
I did a `308 - Permanent Redirect` here over `301 - Permanently Moved`. I'm open to either, but the former seems more semantic to our intentions.
I think it's important for me to recognize that middleware introduces at least a bit of complexity. It does things away from the components/processes that we may be trying to …
> feat(explorer): add middleware to enforce lowercase IDs across relevant routes

- .changeset/silver-ghosts-develop.md
- apps/explorer/components/Address/index.tsx
- apps/explorer/components/Transaction/index.tsx
- libs/explored-types/src/types.ts
In writing the contract status testing up stack, I realized that `ExplorerV2Transaction` was incorrect, particularly around resolution states. This was using web core `V2Transaction`, which matched enough for the `explorer`'s purposes, but there are differences. While it's unfortunate we break out from core a bit more, many of the values are still core imports.
> refactor(explored-types): rewrite ExplorerV2Transaction to match explored

- .changeset/fruity-tools-hope.md
- libs/design-system/src/core/ScrollArea.tsx
Not sure how this broken but there is an issue with ScrollArea display width in certain contexts, eg: `min-w-fit`.
> fix: scroll area width display issue

- .changeset/clean-news-suffer.md
- apps/explorer/components/Transaction/index.tsx
Instead of displaying blank summary and empty input/output list:
Upstream PR adds a dropdown with the transaction dropdown to this page, which will allow people to look at the arbitrary data, which is often the only thing of import happening here.
> refactor(explorer): refine empty transaction ui

- .changeset/early-dancers-tickle.md
- apps/explorer/components/Block/index.tsx
- apps/explorer/components/ExplorerAccordion.tsx
- apps/explorer/components/ExplorerTextarea.tsx
- apps/explorer/components/Transaction/index.tsx
Adds a dropdown to the block and transaction pages (and therefore also the contract page) to allow people to view the request response from `explored` without curling or postman'ing or whatever. I've seen it used in other explorers and I do find it to be useful, even though you can directly request this stuff. We don't display everything in these objects, but people may appreciate a browser-based method to examine it.
> feat(explorer): add dropdown for JSON, add to block and tx pages

- .changeset/plain-pillows-listen.md
- libs/design-system/src/app/AppAuthedLayout/Sidenav.tsx
- Sidenav Logo is now properly positioned on Firefox browsers.
> fix: sidenav logo firefox flex and alignment

- .changeset/sharp-snails-raise.md
- .changeset/soft-papayas-hang.md
- .changeset/tiny-bobcats-fail.md
- apps/renterd-e2e/src/specs/uploads.spec.ts
- apps/renterd/components/DockedControls.tsx
- apps/renterd/components/Files/FilesExplorerModeContextMenu.tsx
- apps/renterd/components/TransfersBar.tsx
- apps/renterd/contexts/filesManager/index.tsx
- apps/renterd/contexts/uploads/useLocalUploads.tsx
- apps/renterd/contexts/uploadsManager/index.tsx
- apps/renterd/lib/multipartUpload.ts
- Fixed an issue where the transfers bar active uploads button did not always work.
- It always assumed a single bucket.
- The transfers bar now lists all buckets with active uploads.
- The transfers bar now shows the total count across all buckets.
> fix(renterd): transfers bar issues and improvements

- .changeset/tender-balloons-notice.md
- apps/explorer/components/Block/index.tsx
- apps/explorer/components/Entity/EntityListItem.tsx
This PR introduces preview badges to the block page transaction list, letting users know what is inside a transaction as opposed to clicking through to hunt for some particular chain action. 
The current badges are `Contract Formation`, `Contract Revision`, `Contract Resolution`, `Host Announcement`, `Arbitrary Data`, and something I'm calling `Spend`. As is, `Spend` is the absence of any other signal AND some kind of siacoin or siafund motion on an address.
Probably needs that manual QA to make sure it tracks.
> feat(explorer): add preview badges for the block page transaction lists

- .changeset/eighty-pumas-explode.md
- apps/explorer-e2e/src/helpers/findTestOutput.ts
- apps/explorer-e2e/src/specs/output.spec.ts
- apps/explorer-e2e/src/specs/tx.spec.ts
- apps/explorer/app/output/[id]/error.tsx
- apps/explorer/app/output/[id]/loading.tsx
- apps/explorer/app/output/[id]/not-found.tsx
- apps/explorer/app/output/[id]/opengraph-image.tsx
- apps/explorer/app/output/[id]/page.tsx
- apps/explorer/components/Layout/Search.tsx
- apps/explorer/components/Output/index.tsx
- apps/explorer/components/OutputSkeleton/index.tsx
- apps/explorer/components/Transaction/OutputListItem.tsx
- apps/explorer/components/Transaction/index.tsx
- apps/explorer/config/routes.ts
Fairly straightforward. Tests included. There were some minor cascading visual tweaks to the outputs list on the transaction page. Since both the ID and address are now clickable (previously only the output title or icon linked to the address), I added title beside these, for clarity. Those extra characters put some strain on the responsiveness of the ID/hash flex container, so I brought down the number of characters displayed in those copyables and adjusted the layout to stack the ID and address more aggressively at smaller viewport widths, rather than hiding the address entirely.
> feat(explorer): add output route, display, and search

- apps/explorer-e2e/project.json
- apps/hostd-e2e/project.json
- apps/renterd-e2e/project.json
- apps/walletd-e2e/project.json
- internal/cluster/README.md
- internal/cluster/project.json
- Adds internal/cluster as an nx project named "cluster" by adding project.json.
- Adds "cluster" as an implicit dependency of all e2e projects. This makes all e2e projects `affected` when cluster source files are modified.
> chore: configure nx implicit go deps

- .changeset/khaki-walls-cough.md
- apps/explorer/lib/hosts.ts
I've seen some results in this top hosts list that have surprised me, and so I looked into this more and realized there were likely a couple of errors in this calculation around knownSince and sectors vs bytes v2 vs. v1. 
While here, I also created a confidence weighting that considers hosts with less than 10 scans to be weaker and also tried to clarify error messages, in case they crop up.
Before:
After:
> fix(explorer): improve host ranking accuracy and consistency

- .changeset/eighty-wolves-protect.md
- .changeset/plenty-beers-cry.md
- libs/design-system/src/lib/contracts.ts
- Fixed an issue where contract timelines would start from 0 when the dataset included a rejected contract. https://github.com/SiaFoundation/hostd/issues/717
- getContractsTimeRangeBlockHeight now ignores start heights of 0.
> fix(hostd): ignore rejected start height 0 in timeline range

- apps/explorer-e2e/src/fixtures/cluster.ts
- Recently much of this logic was added into library method `setupCluster`, this refactors `startCluster` to use this.
> refactor(explorer-e2e): simplify startcluster

- .changeset/eighty-rocks-hide.md
- .changeset/hot-items-divide.md
- .changeset/old-gorillas-shout.md
- .changeset/quick-avocados-accept.md
- .changeset/witty-coats-tickle.md
- .changeset/witty-peas-remember.md
- apps/explorer/app/(main)/tx/[id]/page.tsx
- apps/explorer/components/Block/index.tsx
- apps/explorer/components/ContractView/index.tsx
- apps/explorer/components/Entity/EntityListItem.tsx
- apps/explorer/components/Transaction/TransactionHeader.tsx
- apps/explorer/components/Transaction/index.tsx
- apps/explorer/lib/tx.ts
- libs/explored-types/src/types.ts
- libs/types/src/events.ts
- libs/types/src/v2.ts
- libs/units/src/events.ts
- libs/units/src/transactionTypes.ts
- Transaction and contract and contract resolution types and labels are now fully aligned across all apps.
- Added support for the contract refresh event type. https://github.com/SiaFoundation/hostd/issues/759
- Transaction headers in the explorer now show a badge with the specific type.
- Fixed an issue with the ContractResolution type.
- Fixed v1 ExplorerTransaction arbitraryData type.
- Added support for the arbitrary data event type.
> fix(apps): align txn types

- .changeset/clean-jars-run.md
- apps/explorer/lib/contracts.ts
Last time (I promise)
https://siascan.com/contract/891a8b50e1a2e6b8fcf6d6c5887fef6a3f6e35444ce8ac83e90daa85bcfe9366
Should be "complete" because it has a storage proof. It is currently "in progress"
> Fix v2 contract status logic again

- .changeset/serious-brooms-add.md
- apps/explorer-e2e/src/helpers/findTestContract.ts
- apps/explorer-e2e/src/specs/contract.spec.ts
- apps/explorer/lib/contracts.ts
- The 'in progress' contract status is now 'active' which is consistent with hostd and renterd.
> fix(explorer): align active contract status

- .changeset/tricky-pillows-smoke.md
- apps/renterd/contexts/contracts/index.tsx
- Fixed an issue where the contract timeline would show the current block height indicator at the incorrect height.
- It was showing the estimated height rather than the currentHeight variable which uses node block height unless it is still syncing.
> fix(renterd): contract timeline current block height

- apps/hostd-e2e/src/specs/contracts.spec.ts
- Test was disabled until integrity checks were updated to support v2.
> test(hostd): re-enable integrity check test

- apps/explorer-e2e/src/fixtures/cluster.ts
- apps/explorer-e2e/src/helpers/findTestContract.ts
- apps/explorer-e2e/src/specs/address.spec.ts
- apps/explorer-e2e/src/specs/block.spec.ts
- apps/explorer-e2e/src/specs/contract.spec.ts
- apps/explorer-e2e/src/specs/home.spec.ts
- apps/explorer-e2e/src/specs/host.spec.ts
- apps/explorer-e2e/src/specs/output.spec.ts
- apps/explorer-e2e/src/specs/tx.spec.ts
- apps/hostd-e2e/src/fixtures/beforeTest.ts
- apps/renterd-e2e/src/specs/config.spec.ts
- apps/walletd-e2e/src/specs/seedSendSiacoin.spec.ts
- apps/walletd-e2e/src/specs/seedSendSiafund.spec.ts
- internal/cluster/cmd/clusterd/main.go
- libs/clusterd/src/index.ts
- libs/design-system/src/core/SiacoinField.spec.tsx
- libs/design-system/src/core/SiacoinField.tsx
- libs/design-system/src/form/FieldSiacoin.tsx
- libs/e2e/src/fixtures/preferences.ts
- explorer v1 tests no longer work because even with test contracts they depend on being able to spin up explored and at least 1 hostd which is no longer possible on a v1 network.
- Fixed by removing the network option from cluster and replacing with a testContracts option. This means now the user may specify which test contracts are required v1 or v2 but the resulting network that tests run again is always mined into v2 before other daemons are spun up.
- Fixed other flaky tests relating to sending siacoin in walletd.
> test(e2e): fix v1 explorer tests, flaky tests

- apps/indexd/app/layout.tsx
- apps/indexd/components/Config/index.tsx
- apps/indexd/contexts/config/useFormExchangeRate.tsx
- apps/indexd/hooks/useMedianPrices.tsx
- libs/design-system/src/app/SettingsDialog.tsx
- Configure indexd to use siascan explorer APIs directly for now.
- Once the desired featureset is more clear we will likely move the explorer url to a daemon configuration, right now indexd has a single exchange rate route and does not follow the standard state explorer config like the other daemons.
> feat(indexd): siascan explorer data

- .changeset/metal-guests-find.md
- bun.lock
- libs/design-system/package.json
- libs/design-system/src/app/DataTable/ActiveFilters.tsx
- libs/design-system/src/app/DataTable/DataTable.tsx
- libs/design-system/src/app/DataTable/DataTablePaginatorKnownTotal.tsx
- libs/design-system/src/app/DataTable/useDataTable.tsx
- libs/design-system/src/app/DataTable/useDataTableParams.tsx
- libs/design-system/src/index.ts
- Added TanStack-based DataTable and supporting hooks.
- Initial pass at a TanStack table for use in indexd and eventually it can replace our homegrown table API in all apps.
- Subject to change as we build out indexd and figure out what we need.
- Currently configured to support virtualization, and client-side pagination, faceting, filtering, sorting by default.
- Table data parameters are URL driven and uniquely scoped.
- Table goes for more density than those in our existing apps, also aims to support displaying and manipulating thousands of rows.
- Reason for introducing this is that it will provide solid foundation with strong ecosystem of plugins for column filtering, faceting, ordering, etc and especially virtualization - users have asked for many of these features and they will be …
> feat(design-system): data table

- .changeset/bumpy-comics-yawn.md
- .changeset/major-emus-pay.md
- .changeset/purple-papers-stay.md
- apps/indexd/components/Data/Contracts/contractsColumns.tsx
- apps/indexd/components/Data/Hosts/SidePanelHost.tsx
- apps/indexd/components/Data/Hosts/hostsColumns.tsx
- apps/indexd/components/Data/SidePanel.tsx
- apps/indexd/components/Data/sharedColumns/sizes.ts
- libs/design-system/src/app/DataTable/DataTable.tsx
- Data explorer columns now expand when more space is available.
- DataTable now supports responsive min max column sizing.
- Full IDs and public keys are now displayed in the data explorer cells.
> feat(indexd): responsive column widths

- .changeset/tough-goats-relax.md
- apps/indexd/components/Data/Accounts/AccountsTab.tsx
- apps/indexd/components/Data/Accounts/SidePanelAccount.tsx
- apps/indexd/components/Data/Accounts/SidePanelAccountList.tsx
- apps/indexd/components/Data/Accounts/accountsColumns.tsx
- apps/indexd/components/Data/Accounts/transform.ts
- apps/indexd/components/Data/Accounts/types.ts
- apps/indexd/components/Data/Accounts/useAccounts.tsx
- apps/indexd/components/Data/Views.tsx
- apps/indexd/components/Data/index.tsx
- libs/indexd-types/src/admin.ts
- The data explorer now has an Accounts mode.
- The accounts list response currently returns no data beyond public keys so this is bare bones for now.
> feat(indexd): account explorer

- .changeset/soft-doors-visit.md
- apps/indexd/contexts/config/transform.spec.ts
- apps/indexd/contexts/config/transformDown.ts
- apps/indexd/contexts/config/transformUp.ts
- The daemon units are hastings/byte/block, this converts and displays in sc/tb/month. https://github.com/SiaFoundation/indexd/issues/310
> fix(indexd): update mincollateral units

- .changeset/stupid-brooms-cut.md
- apps/indexd/contexts/config/fields.tsx
- The min collateral inputs now show the /TB/month label.
> fix(indexd): min collateral units label

- .changeset/fresh-books-sell.md
- .changeset/mean-heads-ask.md
- apps/indexd/components/Data/Accounts/useAccounts.tsx
- apps/indexd/components/Data/Contracts/useContracts.tsx
- apps/indexd/components/Data/Hosts/useHosts.tsx
- apps/indexd/components/Data/Keys/KeysTab.tsx
- apps/indexd/components/Data/Keys/SidePanelKey.tsx
- apps/indexd/components/Data/Keys/SidePanelKeyList.tsx
- apps/indexd/components/Data/Keys/keysColumns.tsx
- apps/indexd/components/Data/Keys/transform.ts
- apps/indexd/components/Data/Keys/types.ts
- apps/indexd/components/Data/Keys/useKeys.tsx
- apps/indexd/components/Data/Keys/useKeysParams.ts
- apps/indexd/components/Data/Views.tsx
- apps/indexd/components/Data/index.tsx
- apps/indexd/components/Data/sharedColumns/sizes.ts
- apps/indexd/contexts/dialog.tsx
- apps/indexd/dialogs/ConnectKeyDeleteDialog.tsx
- The data explorer now includes connect keys.
- Connect keys can now be deleted from the detail panel.
> feat(indexd): connect keys

- .changeset/soft-rockets-ring.md
- libs/design-system/src/components/EmptyState/StateError.tsx
- libs/design-system/src/components/EmptyState/StateNoData.tsx
- libs/design-system/src/components/EmptyState/StateNoneMatching.tsx
- libs/design-system/src/components/EmptyState/StateNoneOnPage.tsx
- libs/design-system/src/components/EmptyState/StateNoneYet.tsx
- libs/design-system/src/hooks/useStableCompare.ts
- libs/design-system/src/index.ts
- libs/design-system/src/remoteData/RemoteDataStates.tsx
- libs/design-system/src/remoteData/RemoteDatasetStates.tsx
- libs/design-system/src/remoteData/types.ts
- libs/design-system/src/remoteData/useRemoteData.spec.tsx
- libs/design-system/src/remoteData/useRemoteData.ts
- libs/design-system/src/remoteData/useRemoteDataset.spec.tsx
- libs/design-system/src/remoteData/useRemoteDataset.ts
- libs/design-system/src/remoteData/utils.ts
- Adds remote data and dataset hooks and components.
- These helpers allow fetching data from one or more sources and transforming it into one result.
- The result covers all loading states and factors in previous states when deciding which state the UI should display, eg: after an error or empty state revalidating the same data retains that state rather than flickering to a loading state.
- example usage:
```
const dataset = useRemoteDataset(
{
sourceA, // { isLoading, isValidating, data, error }
sourceB, // { isLoading, isValidating, data, error }
},
({ sourceA, sourceB }) => results, // transform successfully loaded remote sources
{
offset,
filters,
}
)  // DataLoaded<O> | DataLoading | DataError | DataEmptyNoneYet | DataEmptyNoneMatchingFilters | DataEmptyNoneOnPage …
```
> feat(design-system): remote data

- .changeset/tame-tools-clap.md
- libs/design-system/src/app/WalletBalance.tsx
- libs/design-system/src/app/WalletBalanceSideNav.tsx
- The wallet balance components now do not have a tooltip.
> fix(design-system): wallet balance tip
